/* StdLib */
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <string.h>
#include <errno.h>
#include <math.h>

/* McuExpresso */
#include "fsl_gpio.h"
#include "fsl_debug_console.h"
#include "GlobalDef.h"
#include "SubFunc.h"
#include "AudioProc_Conversa.h"

#include "IIR.h"



//---------HPF to remove 20Hz and below --- lower order IIR ----
//---beg---
/*
% Generated by MATLAB(R) 9.3 and Signal Processing Toolbox 7.5.
% Generated on: 19-Nov-2022 09:31:25

% Coefficient Format: Decimal

% Discrete-Time IIR Filter (real)                                                                 
% -------------------------------                                                                 
% Filter Structure    : Direct-Form II, Second-Order Sections                                     
% Number of Sections  : 1                                                                         
% Stable              : Yes                                                                       
% Linear Phase        : No                                                                        

                                                                                                 
SOS Matrix:                                                                                       
1  -2  1  1  -1.944477657767093248253331694286316633224  0.945977936232281213513317652541445568204
                                                                                                  
Scale Values:                                                                                     
0.972613898499843587686086721078027039766     
*/

#define Gain_HPF_20Hz_IIR_2Order_Sect1 0.972613898499843587686086721078027039766

__attribute__((__section__(".dram.data")))
float Coef_HPF_20Hz_IIR_2Order[5]=
{
1*Gain_HPF_20Hz_IIR_2Order_Sect1,  -2*Gain_HPF_20Hz_IIR_2Order_Sect1,  1*Gain_HPF_20Hz_IIR_2Order_Sect1, -1.944477657767093248253331694286316633224,  0.945977936232281213513317652541445568204,
};

float HpFilter1_2Order_Remove20HzBelow[4];         //for Direct1, each biquad needs 4 float space as history state
float HpFilter2_2Order_Remove20HzBelow[4];         //for Direct1, each biquad needs 4 float space as history state

//---end---
//---------HPF to remove 20Hz and below --- lower order IIR ----

bqriirf_df1_handle_t LowPassFilter1;
bqriirf_df1_handle_t LowPassFilter2;

void InitIirFilters(void)
{
	int l;
	int *p;

	memset(HpFilter1_2Order_Remove20HzBelow, 0, sizeof(HpFilter1_2Order_Remove20HzBelow));
	memset(HpFilter2_2Order_Remove20HzBelow, 0, sizeof(HpFilter1_2Order_Remove20HzBelow));

	l= bqriirf_df1_alloc (1);
	p=malloc(l);
	LowPassFilter1= bqriirf_df1_init(p, 1, Coef_HPF_20Hz_IIR_2Order, 0);
	p=malloc(l);
	LowPassFilter2= bqriirf_df1_init(p, 1, Coef_HPF_20Hz_IIR_2Order, 0);
}


