/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define IOPCTL_PIO_ANAMUX_DI 0x00u        /*!<@brief Analog mux is disabled */
#define IOPCTL_PIO_FULLDRIVE_DI 0x00u     /*!<@brief Normal drive */
#define IOPCTL_PIO_FUNC0 0x00u            /*!<@brief Selects pin function 0 */
#define IOPCTL_PIO_FUNC1 0x01u            /*!<@brief Selects pin function 1 */
#define IOPCTL_PIO_INBUF_DI 0x00u         /*!<@brief Disable input buffer function */
#define IOPCTL_PIO_INBUF_EN 0x40u         /*!<@brief Enables input buffer function */
#define IOPCTL_PIO_INV_DI 0x00u           /*!<@brief Input function is not inverted */
#define IOPCTL_PIO_PSEDRAIN_DI 0x00u      /*!<@brief Pseudo Output Drain is disabled */
#define IOPCTL_PIO_PULLDOWN_EN 0x00u      /*!<@brief Enable pull-down function */
#define IOPCTL_PIO_PUPD_DI 0x00u          /*!<@brief Disable pull-up / pull-down function */
#define IOPCTL_PIO_SLEW_RATE_NORMAL 0x00u /*!<@brief Normal mode */

/*! @name FC0_TXD_SCL_MISO_WS (coord G2), J16[1]/U27[3]/U9[12]
  @{ */
/* Routed pin properties */
/*!
 * @brief Peripheral name */
#define BOARD_INITPINS_DEBUG_UART_TXD_PERIPHERAL FLEXCOMM0
/*!
 * @brief Signal name */
#define BOARD_INITPINS_DEBUG_UART_TXD_SIGNAL TXD_SCL_MISO_WS
/*!
 * @brief PORT peripheral base pointer */
#define BOARD_INITPINS_DEBUG_UART_TXD_PORT 0U
/*!
 * @brief PORT pin number */
#define BOARD_INITPINS_DEBUG_UART_TXD_PIN 1U
/*!
 * @brief PORT pin mask */
#define BOARD_INITPINS_DEBUG_UART_TXD_PIN_MASK (1U << 1U)
/* @} */

/*! @name FC0_RXD_SDA_MOSI_DATA (coord G4), JP40[2]
  @{ */
/* Routed pin properties */
/*!
 * @brief Peripheral name */
#define BOARD_INITPINS_DEBUG_UART_RXD_PERIPHERAL FLEXCOMM0
/*!
 * @brief Signal name */
#define BOARD_INITPINS_DEBUG_UART_RXD_SIGNAL RXD_SDA_MOSI_DATA
/*!
 * @brief PORT peripheral base pointer */
#define BOARD_INITPINS_DEBUG_UART_RXD_PORT 0U
/*!
 * @brief PORT pin number */
#define BOARD_INITPINS_DEBUG_UART_RXD_PIN 2U
/*!
 * @brief PORT pin mask */
#define BOARD_INITPINS_DEBUG_UART_RXD_PIN_MASK (1U << 2U)
/* @} */

/*! @name PIO0_10 (coord J3), SW2
  @{ */
/* Routed pin properties */
#define BOARD_INITPINS_SW2_PERIPHERAL GPIO           /*!<@brief Peripheral name */
#define BOARD_INITPINS_SW2_SIGNAL PIO0               /*!<@brief Signal name */
#define BOARD_INITPINS_SW2_CHANNEL 10                /*!<@brief Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_SW2_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_SW2_GPIO_PIN_MASK (1U << 10U) /*!<@brief GPIO pin mask */
#define BOARD_INITPINS_SW2_PORT 0U                   /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_SW2_PIN 10U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_SW2_PIN_MASK (1U << 10U)      /*!<@brief PORT pin mask */
                                                     /* @} */

/*! @name PIO0_29 (coord B10), J27[2]
  @{ */
/* Routed pin properties */
#define BOARD_INITPINS_Output_INT_PERIPHERAL GPIO           /*!<@brief Peripheral name */
#define BOARD_INITPINS_Output_INT_SIGNAL PIO0               /*!<@brief Signal name */
#define BOARD_INITPINS_Output_INT_CHANNEL 29                /*!<@brief Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_Output_INT_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_Output_INT_GPIO_PIN_MASK (1U << 29U) /*!<@brief GPIO pin mask */
#define BOARD_INITPINS_Output_INT_PORT 0U                   /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_Output_INT_PIN 29U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_Output_INT_PIN_MASK (1U << 29U)      /*!<@brief PORT pin mask */
                                                            /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void); /* Function assigned for the Cortex-M33 */

#define IOPCTL_PIO_ANAMUX_DI 0x00u        /*!<@brief Analog mux is disabled */
#define IOPCTL_PIO_FULLDRIVE_DI 0x00u     /*!<@brief Normal drive */
#define IOPCTL_PIO_FUNC1 0x01u            /*!<@brief Selects pin function 1 */
#define IOPCTL_PIO_INBUF_EN 0x40u         /*!<@brief Enables input buffer function */
#define IOPCTL_PIO_INV_DI 0x00u           /*!<@brief Input function is not inverted */
#define IOPCTL_PIO_PSEDRAIN_DI 0x00u      /*!<@brief Pseudo Output Drain is disabled */
#define IOPCTL_PIO_PULLDOWN_EN 0x00u      /*!<@brief Enable pull-down function */
#define IOPCTL_PIO_PUPD_DI 0x00u          /*!<@brief Disable pull-up / pull-down function */
#define IOPCTL_PIO_SLEW_RATE_NORMAL 0x00u /*!<@brief Normal mode */

/*! @name I3C0_SCL (coord N17), J18[1]/U110[13]
  @{ */
/* Routed pin properties */
#define BOARD_I3C_I3C_ICM_SCL_PERIPHERAL I3C            /*!<@brief Peripheral name */
#define BOARD_I3C_I3C_ICM_SCL_SIGNAL SCL                /*!<@brief Signal name */
#define BOARD_I3C_I3C_ICM_SCL_PORT 2U                   /*!<@brief PORT peripheral base pointer */
#define BOARD_I3C_I3C_ICM_SCL_PIN 29U                   /*!<@brief PORT pin number */
#define BOARD_I3C_I3C_ICM_SCL_PIN_MASK (1U << 29U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*! @name I3C0_SDA (coord P16), J18[2]/U110[14]
  @{ */
/* Routed pin properties */
#define BOARD_I3C_I3C_ICM_SDA_PERIPHERAL I3C            /*!<@brief Peripheral name */
#define BOARD_I3C_I3C_ICM_SDA_SIGNAL SDA                /*!<@brief Signal name */
#define BOARD_I3C_I3C_ICM_SDA_PORT 2U                   /*!<@brief PORT peripheral base pointer */
#define BOARD_I3C_I3C_ICM_SDA_PIN 30U                   /*!<@brief PORT pin number */
#define BOARD_I3C_I3C_ICM_SDA_PIN_MASK (1U << 30U)      /*!<@brief PORT pin mask */
                                                        /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void Board_I3C(void); /* Function assigned for the Cortex-M33 */

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
