/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v17.0
processor: MIMXRT685S
package_id: MIMXRT685SFVKB
mcu_data: ksdk2_0
processor_version: 24.12.10
board: MIMXRT685-AUD-EVK
pin_labels:
- {pin_num: F4, pin_signal: PIO0_5/FC0_SSEL2/SCT0_GPI0/SCT0_OUT0/CTIMER_INP1/SEC_PIO0_5/ADC0_0, label: NXP_BQ_MR_N}
- {pin_num: E1, pin_signal: PIO0_6/FC0_SSEL3/SCT0_GPI1/SCT0_OUT1/CTIMER0_MAT0/SEC_PIO0_6/ADC0_8, label: NXP_PWR_SW1}
- {pin_num: A2, pin_signal: PIO0_26/FC3_SSEL2/SCT0_GPI6/SCT0_OUT6/CTIMER_INP7/SEC_PIO0_26/ADC0_3, label: FUN_KEY1_N, identifier: LED_BLUE}
- {pin_num: B3, pin_signal: PIO0_27/FC3_SSEL3/SCT0_GPI7/SCT0_OUT7/CTIMER0_MAT3/SEC_PIO0_27/ADC0_11, label: AP533_RST_N}
- {pin_num: B10, pin_signal: PIO0_29/FC4_TXD_SCL_MISO_WS/CTIMER4_MAT1/I2S_BRIDGE_WS_OUT/SEC_PIO0_29, label: 'J27[2]', identifier: Output_INT}
- {pin_num: B5, pin_signal: PIO1_8/FC5_SSEL2/SCT0_GPI6/CTIMER_INP12/CTIMER1_MAT2/ADC0_4, label: NXP_TOUCH_INT}
- {pin_num: N3, pin_signal: PIO1_15/HS_SPI_SSEL1/CTIMER3_MAT0, label: CHG_INT_N_R}
- {pin_num: T2, pin_signal: PIO2_19/PDM_CLK67/FLEXSPI0B_SS0_N, label: FUN_KEY1_N, identifier: QSPI_B_CS0}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "fsl_iopctl.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
    BOARD_InitPins();
    Board_I3C();
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: cm33, enableClock: 'true'}
- pin_list:
  - {pin_num: G2, peripheral: FLEXCOMM0, signal: TXD_SCL_MISO_WS, pin_signal: PIO0_1/FC0_TXD_SCL_MISO_WS/CTIMER0_MAT1/I2S_BRIDGE_WS_IN/SEC_PIO0_1, direction: OUTPUT,
    pupdena: disabled, pupdsel: pullDown, ibena: disabled, slew_rate: normal, drive: normal, amena: disabled, odena: disabled, iiena: disabled}
  - {pin_num: G4, peripheral: FLEXCOMM0, signal: RXD_SDA_MOSI_DATA, pin_signal: PIO0_2/FC0_RXD_SDA_MOSI_DATA/CTIMER0_MAT2/I2S_BRIDGE_DATA_IN/SEC_PIO0_2, direction: INPUT,
    pupdena: disabled, pupdsel: pullDown, ibena: enabled, slew_rate: normal, drive: normal, amena: disabled, odena: disabled, iiena: disabled}
  - {pin_num: D8, peripheral: FLEXCOMM3, signal: TXD_SCL_MISO_WS, pin_signal: PIO0_22/FC3_TXD_SCL_MISO_WS/CTIMER3_MAT1/TRACEDATA(0)/SEC_PIO0_22, direction: OUTPUT}
  - {pin_num: B3, peripheral: GPIO, signal: 'PIO0, 27', pin_signal: PIO0_27/FC3_SSEL3/SCT0_GPI7/SCT0_OUT7/CTIMER0_MAT3/SEC_PIO0_27/ADC0_11}
  - {pin_num: E1, peripheral: GPIO, signal: 'PIO0, 6', pin_signal: PIO0_6/FC0_SSEL3/SCT0_GPI1/SCT0_OUT1/CTIMER0_MAT0/SEC_PIO0_6/ADC0_8}
  - {pin_num: F4, peripheral: GPIO, signal: 'PIO0, 5', pin_signal: PIO0_5/FC0_SSEL2/SCT0_GPI0/SCT0_OUT0/CTIMER_INP1/SEC_PIO0_5/ADC0_0, ibena: enabled}
  - {pin_num: A2, peripheral: GPIO, signal: 'PIO0, 26', pin_signal: PIO0_26/FC3_SSEL2/SCT0_GPI6/SCT0_OUT6/CTIMER_INP7/SEC_PIO0_26/ADC0_3, ibena: enabled}
  - {pin_num: L2, peripheral: FLEXCOMM14, signal: SCK, pin_signal: PIO1_11/HS_SPI_SCK/CTIMER2_MAT0/FLEXSPI0B_DATA0, ibena: enabled}
  - {pin_num: N1, peripheral: FLEXCOMM14, signal: MOSI, pin_signal: PIO1_13/HS_SPI_MOSI/CTIMER2_MAT2/FLEXSPI0B_DATA2, ibena: enabled}
  - {pin_num: M2, peripheral: FLEXCOMM14, signal: MISO, pin_signal: PIO1_12/HS_SPI_MISO/CTIMER2_MAT1/FLEXSPI0B_DATA1, ibena: enabled}
  - {pin_num: N2, peripheral: FLEXCOMM14, signal: SSEL0, pin_signal: PIO1_14/HS_SPI_SSEL0/CTIMER2_MAT3/FLEXSPI0B_DATA3, ibena: enabled}
  - {pin_num: E2, peripheral: GPIO, signal: 'PIO2, 15', pin_signal: PIO2_15/SCT0_OUT9/CLKIN/CMP0_D}
  - {pin_num: B5, peripheral: GPIO, signal: 'PIO1, 8', pin_signal: PIO1_8/FC5_SSEL2/SCT0_GPI6/CTIMER_INP12/CTIMER1_MAT2/ADC0_4, ibena: enabled}
  - {pin_num: N3, peripheral: GPIO, signal: 'PIO1, 15', pin_signal: PIO1_15/HS_SPI_SSEL1/CTIMER3_MAT0, ibena: enabled}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
/* Function assigned for the Cortex-M33 */
void BOARD_InitPins(void)
{

    const uint32_t DEBUG_UART_TXD = (/* Pin is configured as FC0_TXD_SCL_MISO_WS */
                                     IOPCTL_PIO_FUNC1 |
                                     /* Disable pull-up / pull-down function */
                                     IOPCTL_PIO_PUPD_DI |
                                     /* Enable pull-down function */
                                     IOPCTL_PIO_PULLDOWN_EN |
                                     /* Disable input buffer function */
                                     IOPCTL_PIO_INBUF_DI |
                                     /* Normal mode */
                                     IOPCTL_PIO_SLEW_RATE_NORMAL |
                                     /* Normal drive */
                                     IOPCTL_PIO_FULLDRIVE_DI |
                                     /* Analog mux is disabled */
                                     IOPCTL_PIO_ANAMUX_DI |
                                     /* Pseudo Output Drain is disabled */
                                     IOPCTL_PIO_PSEDRAIN_DI |
                                     /* Input function is not inverted */
                                     IOPCTL_PIO_INV_DI);
    /* PORT0 PIN1 (coords: G2) is configured as FC0_TXD_SCL_MISO_WS */
    IOPCTL_PinMuxSet(IOPCTL, BOARD_INITPINS_DEBUG_UART_TXD_PORT, BOARD_INITPINS_DEBUG_UART_TXD_PIN, DEBUG_UART_TXD);

    const uint32_t DEBUG_UART_RXD = (/* Pin is configured as FC0_RXD_SDA_MOSI_DATA */
                                     IOPCTL_PIO_FUNC1 |
                                     /* Disable pull-up / pull-down function */
                                     IOPCTL_PIO_PUPD_DI |
                                     /* Enable pull-down function */
                                     IOPCTL_PIO_PULLDOWN_EN |
                                     /* Enables input buffer function */
                                     IOPCTL_PIO_INBUF_EN |
                                     /* Normal mode */
                                     IOPCTL_PIO_SLEW_RATE_NORMAL |
                                     /* Normal drive */
                                     IOPCTL_PIO_FULLDRIVE_DI |
                                     /* Analog mux is disabled */
                                     IOPCTL_PIO_ANAMUX_DI |
                                     /* Pseudo Output Drain is disabled */
                                     IOPCTL_PIO_PSEDRAIN_DI |
                                     /* Input function is not inverted */
                                     IOPCTL_PIO_INV_DI);
    /* PORT0 PIN2 (coords: G4) is configured as FC0_RXD_SDA_MOSI_DATA */
    IOPCTL_PinMuxSet(IOPCTL, BOARD_INITPINS_DEBUG_UART_RXD_PORT, BOARD_INITPINS_DEBUG_UART_RXD_PIN, DEBUG_UART_RXD);

    const uint32_t port0_pin22_config = (/* Pin is configured as FC3_TXD_SCL_MISO_WS */
                                         IOPCTL_PIO_FUNC1 |
                                         /* Disable pull-up / pull-down function */
                                         IOPCTL_PIO_PUPD_DI |
                                         /* Enable pull-down function */
                                         IOPCTL_PIO_PULLDOWN_EN |
                                         /* Disable input buffer function */
                                         IOPCTL_PIO_INBUF_DI |
                                         /* Normal mode */
                                         IOPCTL_PIO_SLEW_RATE_NORMAL |
                                         /* Normal drive */
                                         IOPCTL_PIO_FULLDRIVE_DI |
                                         /* Analog mux is disabled */
                                         IOPCTL_PIO_ANAMUX_DI |
                                         /* Pseudo Output Drain is disabled */
                                         IOPCTL_PIO_PSEDRAIN_DI |
                                         /* Input function is not inverted */
                                         IOPCTL_PIO_INV_DI);
    /* PORT0 PIN22 (coords: D8) is configured as FC3_TXD_SCL_MISO_WS */
    IOPCTL_PinMuxSet(IOPCTL, 0U, 22U, port0_pin22_config);

    const uint32_t LED_BLUE = (/* Pin is configured as PIO0_26 */
                               IOPCTL_PIO_FUNC0 |
                               /* Disable pull-up / pull-down function */
                               IOPCTL_PIO_PUPD_DI |
                               /* Enable pull-down function */
                               IOPCTL_PIO_PULLDOWN_EN |
                               /* Enables input buffer function */
                               IOPCTL_PIO_INBUF_EN |
                               /* Normal mode */
                               IOPCTL_PIO_SLEW_RATE_NORMAL |
                               /* Normal drive */
                               IOPCTL_PIO_FULLDRIVE_DI |
                               /* Analog mux is disabled */
                               IOPCTL_PIO_ANAMUX_DI |
                               /* Pseudo Output Drain is disabled */
                               IOPCTL_PIO_PSEDRAIN_DI |
                               /* Input function is not inverted */
                               IOPCTL_PIO_INV_DI);
    /* PORT0 PIN26 (coords: A2) is configured as PIO0_26 */
    IOPCTL_PinMuxSet(IOPCTL, BOARD_INITPINS_LED_BLUE_PORT, BOARD_INITPINS_LED_BLUE_PIN, LED_BLUE);

    const uint32_t port0_pin27_config = (/* Pin is configured as PIO0_27 */
                                         IOPCTL_PIO_FUNC0 |
                                         /* Disable pull-up / pull-down function */
                                         IOPCTL_PIO_PUPD_DI |
                                         /* Enable pull-down function */
                                         IOPCTL_PIO_PULLDOWN_EN |
                                         /* Disable input buffer function */
                                         IOPCTL_PIO_INBUF_DI |
                                         /* Normal mode */
                                         IOPCTL_PIO_SLEW_RATE_NORMAL |
                                         /* Normal drive */
                                         IOPCTL_PIO_FULLDRIVE_DI |
                                         /* Analog mux is disabled */
                                         IOPCTL_PIO_ANAMUX_DI |
                                         /* Pseudo Output Drain is disabled */
                                         IOPCTL_PIO_PSEDRAIN_DI |
                                         /* Input function is not inverted */
                                         IOPCTL_PIO_INV_DI);
    /* PORT0 PIN27 (coords: B3) is configured as PIO0_27 */
    IOPCTL_PinMuxSet(IOPCTL, 0U, 27U, port0_pin27_config);

    const uint32_t port0_pin5_config = (/* Pin is configured as PIO0_5 */
                                        IOPCTL_PIO_FUNC0 |
                                        /* Disable pull-up / pull-down function */
                                        IOPCTL_PIO_PUPD_DI |
                                        /* Enable pull-down function */
                                        IOPCTL_PIO_PULLDOWN_EN |
                                        /* Enables input buffer function */
                                        IOPCTL_PIO_INBUF_EN |
                                        /* Normal mode */
                                        IOPCTL_PIO_SLEW_RATE_NORMAL |
                                        /* Normal drive */
                                        IOPCTL_PIO_FULLDRIVE_DI |
                                        /* Analog mux is disabled */
                                        IOPCTL_PIO_ANAMUX_DI |
                                        /* Pseudo Output Drain is disabled */
                                        IOPCTL_PIO_PSEDRAIN_DI |
                                        /* Input function is not inverted */
                                        IOPCTL_PIO_INV_DI);
    /* PORT0 PIN5 (coords: F4) is configured as PIO0_5 */
    IOPCTL_PinMuxSet(IOPCTL, 0U, 5U, port0_pin5_config);

    const uint32_t port0_pin6_config = (/* Pin is configured as PIO0_6 */
                                        IOPCTL_PIO_FUNC0 |
                                        /* Disable pull-up / pull-down function */
                                        IOPCTL_PIO_PUPD_DI |
                                        /* Enable pull-down function */
                                        IOPCTL_PIO_PULLDOWN_EN |
                                        /* Disable input buffer function */
                                        IOPCTL_PIO_INBUF_DI |
                                        /* Normal mode */
                                        IOPCTL_PIO_SLEW_RATE_NORMAL |
                                        /* Normal drive */
                                        IOPCTL_PIO_FULLDRIVE_DI |
                                        /* Analog mux is disabled */
                                        IOPCTL_PIO_ANAMUX_DI |
                                        /* Pseudo Output Drain is disabled */
                                        IOPCTL_PIO_PSEDRAIN_DI |
                                        /* Input function is not inverted */
                                        IOPCTL_PIO_INV_DI);
    /* PORT0 PIN6 (coords: E1) is configured as PIO0_6 */
    IOPCTL_PinMuxSet(IOPCTL, 0U, 6U, port0_pin6_config);

    const uint32_t QSPI_B_DATA0 = (/* Pin is configured as HS_SPI_SCK */
                                   IOPCTL_PIO_FUNC1 |
                                   /* Disable pull-up / pull-down function */
                                   IOPCTL_PIO_PUPD_DI |
                                   /* Enable pull-down function */
                                   IOPCTL_PIO_PULLDOWN_EN |
                                   /* Enables input buffer function */
                                   IOPCTL_PIO_INBUF_EN |
                                   /* Normal mode */
                                   IOPCTL_PIO_SLEW_RATE_NORMAL |
                                   /* Normal drive */
                                   IOPCTL_PIO_FULLDRIVE_DI |
                                   /* Analog mux is disabled */
                                   IOPCTL_PIO_ANAMUX_DI |
                                   /* Pseudo Output Drain is disabled */
                                   IOPCTL_PIO_PSEDRAIN_DI |
                                   /* Input function is not inverted */
                                   IOPCTL_PIO_INV_DI);
    /* PORT1 PIN11 (coords: L2) is configured as HS_SPI_SCK */
    IOPCTL_PinMuxSet(IOPCTL, BOARD_INITPINS_QSPI_B_DATA0_PORT, BOARD_INITPINS_QSPI_B_DATA0_PIN, QSPI_B_DATA0);

    const uint32_t QSPI_B_DATA1 = (/* Pin is configured as HS_SPI_MISO */
                                   IOPCTL_PIO_FUNC1 |
                                   /* Disable pull-up / pull-down function */
                                   IOPCTL_PIO_PUPD_DI |
                                   /* Enable pull-down function */
                                   IOPCTL_PIO_PULLDOWN_EN |
                                   /* Enables input buffer function */
                                   IOPCTL_PIO_INBUF_EN |
                                   /* Normal mode */
                                   IOPCTL_PIO_SLEW_RATE_NORMAL |
                                   /* Normal drive */
                                   IOPCTL_PIO_FULLDRIVE_DI |
                                   /* Analog mux is disabled */
                                   IOPCTL_PIO_ANAMUX_DI |
                                   /* Pseudo Output Drain is disabled */
                                   IOPCTL_PIO_PSEDRAIN_DI |
                                   /* Input function is not inverted */
                                   IOPCTL_PIO_INV_DI);
    /* PORT1 PIN12 (coords: M2) is configured as HS_SPI_MISO */
    IOPCTL_PinMuxSet(IOPCTL, BOARD_INITPINS_QSPI_B_DATA1_PORT, BOARD_INITPINS_QSPI_B_DATA1_PIN, QSPI_B_DATA1);

    const uint32_t QSPI_B_DATA2 = (/* Pin is configured as HS_SPI_MOSI */
                                   IOPCTL_PIO_FUNC1 |
                                   /* Disable pull-up / pull-down function */
                                   IOPCTL_PIO_PUPD_DI |
                                   /* Enable pull-down function */
                                   IOPCTL_PIO_PULLDOWN_EN |
                                   /* Enables input buffer function */
                                   IOPCTL_PIO_INBUF_EN |
                                   /* Normal mode */
                                   IOPCTL_PIO_SLEW_RATE_NORMAL |
                                   /* Normal drive */
                                   IOPCTL_PIO_FULLDRIVE_DI |
                                   /* Analog mux is disabled */
                                   IOPCTL_PIO_ANAMUX_DI |
                                   /* Pseudo Output Drain is disabled */
                                   IOPCTL_PIO_PSEDRAIN_DI |
                                   /* Input function is not inverted */
                                   IOPCTL_PIO_INV_DI);
    /* PORT1 PIN13 (coords: N1) is configured as HS_SPI_MOSI */
    IOPCTL_PinMuxSet(IOPCTL, BOARD_INITPINS_QSPI_B_DATA2_PORT, BOARD_INITPINS_QSPI_B_DATA2_PIN, QSPI_B_DATA2);

    const uint32_t QSPI_B_DATA3 = (/* Pin is configured as HS_SPI_SSEL0 */
                                   IOPCTL_PIO_FUNC1 |
                                   /* Disable pull-up / pull-down function */
                                   IOPCTL_PIO_PUPD_DI |
                                   /* Enable pull-down function */
                                   IOPCTL_PIO_PULLDOWN_EN |
                                   /* Enables input buffer function */
                                   IOPCTL_PIO_INBUF_EN |
                                   /* Normal mode */
                                   IOPCTL_PIO_SLEW_RATE_NORMAL |
                                   /* Normal drive */
                                   IOPCTL_PIO_FULLDRIVE_DI |
                                   /* Analog mux is disabled */
                                   IOPCTL_PIO_ANAMUX_DI |
                                   /* Pseudo Output Drain is disabled */
                                   IOPCTL_PIO_PSEDRAIN_DI |
                                   /* Input function is not inverted */
                                   IOPCTL_PIO_INV_DI);
    /* PORT1 PIN14 (coords: N2) is configured as HS_SPI_SSEL0 */
    IOPCTL_PinMuxSet(IOPCTL, BOARD_INITPINS_QSPI_B_DATA3_PORT, BOARD_INITPINS_QSPI_B_DATA3_PIN, QSPI_B_DATA3);

    const uint32_t port1_pin15_config = (/* Pin is configured as PIO1_15 */
                                         IOPCTL_PIO_FUNC0 |
                                         /* Disable pull-up / pull-down function */
                                         IOPCTL_PIO_PUPD_DI |
                                         /* Enable pull-down function */
                                         IOPCTL_PIO_PULLDOWN_EN |
                                         /* Enables input buffer function */
                                         IOPCTL_PIO_INBUF_EN |
                                         /* Normal mode */
                                         IOPCTL_PIO_SLEW_RATE_NORMAL |
                                         /* Normal drive */
                                         IOPCTL_PIO_FULLDRIVE_DI |
                                         /* Analog mux is disabled */
                                         IOPCTL_PIO_ANAMUX_DI |
                                         /* Pseudo Output Drain is disabled */
                                         IOPCTL_PIO_PSEDRAIN_DI |
                                         /* Input function is not inverted */
                                         IOPCTL_PIO_INV_DI);
    /* PORT1 PIN15 (coords: N3) is configured as PIO1_15 */
    IOPCTL_PinMuxSet(IOPCTL, 1U, 15U, port1_pin15_config);

    const uint32_t port1_pin8_config = (/* Pin is configured as PIO1_8 */
                                        IOPCTL_PIO_FUNC0 |
                                        /* Disable pull-up / pull-down function */
                                        IOPCTL_PIO_PUPD_DI |
                                        /* Enable pull-down function */
                                        IOPCTL_PIO_PULLDOWN_EN |
                                        /* Enables input buffer function */
                                        IOPCTL_PIO_INBUF_EN |
                                        /* Normal mode */
                                        IOPCTL_PIO_SLEW_RATE_NORMAL |
                                        /* Normal drive */
                                        IOPCTL_PIO_FULLDRIVE_DI |
                                        /* Analog mux is disabled */
                                        IOPCTL_PIO_ANAMUX_DI |
                                        /* Pseudo Output Drain is disabled */
                                        IOPCTL_PIO_PSEDRAIN_DI |
                                        /* Input function is not inverted */
                                        IOPCTL_PIO_INV_DI);
    /* PORT1 PIN8 (coords: B5) is configured as PIO1_8 */
    IOPCTL_PinMuxSet(IOPCTL, 1U, 8U, port1_pin8_config);

    const uint32_t port2_pin15_config = (/* Pin is configured as PIO2_15 */
                                         IOPCTL_PIO_FUNC0 |
                                         /* Disable pull-up / pull-down function */
                                         IOPCTL_PIO_PUPD_DI |
                                         /* Enable pull-down function */
                                         IOPCTL_PIO_PULLDOWN_EN |
                                         /* Disable input buffer function */
                                         IOPCTL_PIO_INBUF_DI |
                                         /* Normal mode */
                                         IOPCTL_PIO_SLEW_RATE_NORMAL |
                                         /* Normal drive */
                                         IOPCTL_PIO_FULLDRIVE_DI |
                                         /* Analog mux is disabled */
                                         IOPCTL_PIO_ANAMUX_DI |
                                         /* Pseudo Output Drain is disabled */
                                         IOPCTL_PIO_PSEDRAIN_DI |
                                         /* Input function is not inverted */
                                         IOPCTL_PIO_INV_DI);
    /* PORT2 PIN15 (coords: E2) is configured as PIO2_15 */
    IOPCTL_PinMuxSet(IOPCTL, 2U, 15U, port2_pin15_config);
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
Board_I3C:
- options: {callFromInitBoot: 'true', coreID: cm33, enableClock: 'true'}
- pin_list:
  - {pin_num: N17, peripheral: I3C, signal: SCL, pin_signal: PIO2_29/I3C0_SCL/SCT0_OUT0/CLKOUT, ibena: enabled}
  - {pin_num: P16, peripheral: I3C, signal: SDA, pin_signal: PIO2_30/I3C0_SDA/SCT0_OUT3/CLKIN/CMP0_OUT, ibena: enabled}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : Board_I3C
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
/* Function assigned for the Cortex-M33 */
void Board_I3C(void)
{

    const uint32_t I3C_ICM_SCL = (/* Pin is configured as I3C0_SCL */
                                  IOPCTL_PIO_FUNC1 |
                                  /* Disable pull-up / pull-down function */
                                  IOPCTL_PIO_PUPD_DI |
                                  /* Enable pull-down function */
                                  IOPCTL_PIO_PULLDOWN_EN |
                                  /* Enables input buffer function */
                                  IOPCTL_PIO_INBUF_EN |
                                  /* Normal mode */
                                  IOPCTL_PIO_SLEW_RATE_NORMAL |
                                  /* Normal drive */
                                  IOPCTL_PIO_FULLDRIVE_DI |
                                  /* Analog mux is disabled */
                                  IOPCTL_PIO_ANAMUX_DI |
                                  /* Pseudo Output Drain is disabled */
                                  IOPCTL_PIO_PSEDRAIN_DI |
                                  /* Input function is not inverted */
                                  IOPCTL_PIO_INV_DI);
    /* PORT2 PIN29 (coords: N17) is configured as I3C0_SCL */
    IOPCTL_PinMuxSet(IOPCTL, BOARD_I3C_I3C_ICM_SCL_PORT, BOARD_I3C_I3C_ICM_SCL_PIN, I3C_ICM_SCL);

    const uint32_t I3C_ICM_SDA = (/* Pin is configured as I3C0_SDA */
                                  IOPCTL_PIO_FUNC1 |
                                  /* Disable pull-up / pull-down function */
                                  IOPCTL_PIO_PUPD_DI |
                                  /* Enable pull-down function */
                                  IOPCTL_PIO_PULLDOWN_EN |
                                  /* Enables input buffer function */
                                  IOPCTL_PIO_INBUF_EN |
                                  /* Normal mode */
                                  IOPCTL_PIO_SLEW_RATE_NORMAL |
                                  /* Normal drive */
                                  IOPCTL_PIO_FULLDRIVE_DI |
                                  /* Analog mux is disabled */
                                  IOPCTL_PIO_ANAMUX_DI |
                                  /* Pseudo Output Drain is disabled */
                                  IOPCTL_PIO_PSEDRAIN_DI |
                                  /* Input function is not inverted */
                                  IOPCTL_PIO_INV_DI);
    /* PORT2 PIN30 (coords: P16) is configured as I3C0_SDA */
    IOPCTL_PinMuxSet(IOPCTL, BOARD_I3C_I3C_ICM_SDA_PORT, BOARD_I3C_I3C_ICM_SDA_PIN, I3C_ICM_SDA);
}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
