/**
 * @file aw933xx_param.c
 * @brief this file parse the config generated by AWINIC UI.
 *
 */
#include <string.h>
#include "aw933xx_param.h"
#include "aw_type.h"


AW_U32 aw933xx_reg_data[PARAM_REG_BUF_MAX] = { 0 };
AW_CS_CH_S g_cs_ch_select = { 0 };
AW_SLIDER_CH_S g_slider_ch_cfg = { 0 };
AW_PARRAM_INIT_CFG g_param_init_cfg = { 0 };
REG_CFG_ADDR_S g_reg_cfg_addr = { 0 };
REG_CFG_DATA_S g_reg_cfg_data = { 0 };

AW_CS_CH_S *aw_get_cs_ch_func(void)
{
	return &g_cs_ch_select;
}

AW_SLIDER_CH_S *aw_get_slider_ch_func(void)
{
	return &g_slider_ch_cfg;
}

AW_PARRAM_INIT_CFG *aw_get_param_init_func(void)
{
	return &g_param_init_cfg;
}

REG_CFG_ADDR_S *aw_get_reg_addr_func(void)
{
	return &g_reg_cfg_addr;
}

REG_CFG_DATA_S *aw_get_reg_data_func(void)
{
	return &g_reg_cfg_data;
}

static void aw_reg_addr_data_cfg(void)
{
	AW_U16 i = 0;

	REG_CFG_ADDR_S *p_reg_cfg_addr = aw_get_reg_addr_func();
	REG_CFG_DATA_S *p_reg_cfg_data = aw_get_reg_data_func();

	if ((p_reg_cfg_addr != NULL) &&  (p_reg_cfg_data != NULL)) {
		aw933xx_reg_data[0] = p_reg_cfg_addr->addr_scan_ctrl0;
		aw933xx_reg_data[1] = p_reg_cfg_data->data_scan_ctrl0;
		aw933xx_reg_data[2] = p_reg_cfg_addr->addr_scan_ctrl1;
		aw933xx_reg_data[3] = p_reg_cfg_data->data_scan_ctrl1;
		aw933xx_reg_data[4] = p_reg_cfg_addr->addr_scan_ctrl2;
		aw933xx_reg_data[5] = p_reg_cfg_data->data_scan_ctrl2;
		aw933xx_reg_data[6] = p_reg_cfg_addr->addr_scan_ctrl3;
		aw933xx_reg_data[7] = p_reg_cfg_data->data_scan_ctrl3;
		for (i = 0; i < AW_CHANNEL_NUM_MAX; i++) {
			aw933xx_reg_data[6 + 2 + PER_GROUP_PARAM_NUM * i] = p_reg_cfg_addr->addr_chl_sel0[i];
			aw933xx_reg_data[6 + 3 + PER_GROUP_PARAM_NUM * i] = p_reg_cfg_data->data_chl_sel0[i];
			aw933xx_reg_data[6 + 4 + PER_GROUP_PARAM_NUM * i] = p_reg_cfg_addr->addr_chl_sel1[i];
			aw933xx_reg_data[6 + 5 + PER_GROUP_PARAM_NUM * i] = p_reg_cfg_data->data_chl_sel1[i];
			aw933xx_reg_data[6 + 6 + PER_GROUP_PARAM_NUM * i] = p_reg_cfg_addr->addr_touch_th_x[i];
			aw933xx_reg_data[6 + 7 + PER_GROUP_PARAM_NUM * i] = p_reg_cfg_data->data_touch_th_x[i];
			aw933xx_reg_data[6 + 8 + PER_GROUP_PARAM_NUM * i] = p_reg_cfg_addr->addr_touch_th_y[i];
			aw933xx_reg_data[6 + 9 + PER_GROUP_PARAM_NUM * i] = p_reg_cfg_data->data_touch_th_y[i];
			aw933xx_reg_data[6 + 10 + PER_GROUP_PARAM_NUM * i] = p_reg_cfg_addr->addr_leave_th_x[i];
			aw933xx_reg_data[6 + 11 + PER_GROUP_PARAM_NUM * i] = p_reg_cfg_data->data_leave_th_x[i];
			aw933xx_reg_data[6 + 12 + PER_GROUP_PARAM_NUM * i] = p_reg_cfg_addr->addr_leave_th_y[i];
			aw933xx_reg_data[6 + 13 + PER_GROUP_PARAM_NUM * i] = p_reg_cfg_data->data_leave_th_y[i];
			aw933xx_reg_data[6 + 14 + PER_GROUP_PARAM_NUM * i] = p_reg_cfg_addr->addr_button_cfg0[i];
			aw933xx_reg_data[6 + 15 + PER_GROUP_PARAM_NUM * i] = p_reg_cfg_data->data_button_cfg0[i];
			aw933xx_reg_data[6 + 16 + PER_GROUP_PARAM_NUM * i] = p_reg_cfg_addr->addr_button_cfg1[i];
			aw933xx_reg_data[6 + 17 + PER_GROUP_PARAM_NUM * i] = p_reg_cfg_data->data_button_cfg1[i];
			aw933xx_reg_data[6 + 18 + PER_GROUP_PARAM_NUM * i] = p_reg_cfg_addr->addr_longpresss_cfg0[i];
			aw933xx_reg_data[6 + 19 + PER_GROUP_PARAM_NUM * i] = p_reg_cfg_data->data_longpresss_cfg0[i];
			aw933xx_reg_data[6 + 20 + PER_GROUP_PARAM_NUM * i] = p_reg_cfg_addr->addr_longpresss_cfg1[i];
			aw933xx_reg_data[6 + 21 + PER_GROUP_PARAM_NUM * i] = p_reg_cfg_data->data_longpresss_cfg1[i];
			aw933xx_reg_data[6 + 22 + PER_GROUP_PARAM_NUM * i] = p_reg_cfg_addr->addr_pos_cal_x[i];
			aw933xx_reg_data[6 + 23 + PER_GROUP_PARAM_NUM * i] = p_reg_cfg_data->data_pos_cal_x[i];
			aw933xx_reg_data[6 + 24 + PER_GROUP_PARAM_NUM * i] = p_reg_cfg_addr->addr_pos_cal_y[i];
			aw933xx_reg_data[6 + 25 + PER_GROUP_PARAM_NUM * i] = p_reg_cfg_data->data_pos_cal_y[i];
			aw933xx_reg_data[6 + 26 + PER_GROUP_PARAM_NUM * i] = p_reg_cfg_addr->addr_sld_cfg[i];
			aw933xx_reg_data[6 + 27 + PER_GROUP_PARAM_NUM * i] = p_reg_cfg_data->data_sld_cfg[i];
			aw933xx_reg_data[6 + 28 + PER_GROUP_PARAM_NUM * i] = p_reg_cfg_addr->addr_sld_limit_th[i];
			aw933xx_reg_data[6 + 29 + PER_GROUP_PARAM_NUM * i] = p_reg_cfg_data->data_sld_limit_th[i];
		}
	}
}

static void aw_reg_data_cfg(REG_CFG_STRUCT *reg_config_struct)
{
	AW_U16 i = 0;
	AW_U32 channel_en = 0;
	REG_CFG_DATA_S *p_reg_cfg_data = aw_get_reg_data_func();

	if (p_reg_cfg_data != NULL) {
		for (i = 0; i < AW_CHANNEL_NUM_MAX; i++)
			channel_en |= (reg_config_struct->reg_scan_ctrl0.field_chen_ch[i] << i);

		p_reg_cfg_data->data_scan_ctrl0 = channel_en;
		p_reg_cfg_data->data_scan_ctrl1 = channel_en;
		p_reg_cfg_data->data_scan_ctrl2 = channel_en;
		p_reg_cfg_data->data_scan_ctrl3 = reg_config_struct->reg_scan_ctrl0.field_scan_period;

		for (i = 0; i < AW_CHANNEL_NUM_MAX; i++) {
			p_reg_cfg_data->data_chl_sel0[i] =
				(reg_config_struct->reg_chl_sel0[i].field_cs_sel[0] == 0 ? HZ : MEASURED_INPUT) << ((reg_config_struct->reg_chl_sel0[i].field_cs_sel[0] - 1) * 3);
			p_reg_cfg_data->data_chl_sel1[i] =
				(reg_config_struct->reg_chl_sel0[i].field_cs_sel[0] <= 10 ? HZ : MEASURED_INPUT) << (((reg_config_struct->reg_chl_sel0[i].field_cs_sel[0] - 1) % 10) * 3);
			p_reg_cfg_data->data_touch_th_x[i] = reg_config_struct->reg_touch_th_x[i].field_touch_th_x;
			p_reg_cfg_data->data_leave_th_x[i] = reg_config_struct->reg_leave_th_x[i].field_leave_th_x;
			p_reg_cfg_data->data_touch_th_y[i] = reg_config_struct->reg_touch_th_y[i].field_touch_th_y;
			p_reg_cfg_data->data_leave_th_y[i] = reg_config_struct->reg_leave_th_y[i].field_leave_th_y;
			p_reg_cfg_data->data_button_cfg0[i] = ((reg_config_struct->reg_button_cfg0[i].field_irq_en << CAP_TOUCH_IRQ_EN_SLD0_POS) |
							       (reg_config_struct->reg_button_cfg0[i].field_ctl_func << CAP_CONTROL_FUNC_SLD0_POS) |
							       (reg_config_struct->reg_button_cfg0[i].field_touch_deb_th << CAP_TOUCH_DEB_TH_SLD0_POS) |
							       (reg_config_struct->reg_button_cfg0[i].field_ch_num_y << CAP_CHANNEL_NUM_Y_SLD0_POS) |
							       (reg_config_struct->reg_button_cfg0[i].field_ch_num_x << CAP_CHANNEL_NUM_X_SLD0_POS) |
							       (reg_config_struct->reg_button_cfg0[i].field_start_index << CAP_START_INDEX_SLD0_POS));
			p_reg_cfg_data->data_button_cfg1[i] =
				((reg_config_struct->reg_button_cfg1[i].field_touch_time_period << CAP_TOUCH_TIME_PERIOD_SLD0_POS) | reg_config_struct->reg_button_cfg1[i].field_click_interval);
			p_reg_cfg_data->data_longpresss_cfg0[i] =
				((reg_config_struct->reg_longpresss_cfg0[i].field_longpress_th2 << CAP_LONG_LONG_PRESS_TH_SLD0_POS) | reg_config_struct->reg_longpresss_cfg0[i].field_longpress_th1);
			p_reg_cfg_data->data_longpresss_cfg1[i] = reg_config_struct->reg_longpresss_cfg1[i].field_longpress_th3;
			p_reg_cfg_data->data_pos_cal_x[i] = reg_config_struct->reg_pos_cal_x[i].field_pos_cal_th_x;
			p_reg_cfg_data->data_pos_cal_y[i] = reg_config_struct->reg_pos_cal_y[i].field_pos_cal_th_y;
			p_reg_cfg_data->data_sld_cfg[i] = ((reg_config_struct->reg_sld_cfg[i].field_move_recip_th << CAP_MOVE_RECIP_TH_SLD0_POS) |
							   (reg_config_struct->reg_sld_cfg[i].field_spe_linear_en << CAP_SPE_LINEAR_EN_SLD0_POS) |
							   (reg_config_struct->reg_sld_cfg[i].field_con_sld_en << CAP_CONTINUE_SLD_EN_SLD0_POS) |
							   (reg_config_struct->reg_sld_cfg[i].field_con_sld_mode << CAP_CONTINUE_SLD_MODE_SLD0_POS) |
							   (reg_config_struct->reg_sld_cfg[i].field_sld_type << CAP_SLD_TYPE_SLD0_POS));
			p_reg_cfg_data->data_sld_limit_th[i] =
				((reg_config_struct->reg_sld_limit_th[i].field_sld_limit_th_y << CAP_SLD_LIMIT_TH_Y_SLD0_POS) | reg_config_struct->reg_sld_limit_th[i].field_sld_limit_th_x);
		}
	}
}

static void aw_reg_addr_cfg(void)
{
	AW_U16 i = 0;
	REG_CFG_ADDR_S *p_reg_cfg_addr = aw_get_reg_addr_func();

	if (p_reg_cfg_addr != NULL) {
		p_reg_cfg_addr->addr_scan_ctrl0 = REG_SCAN_CTRL_ADDR;
		p_reg_cfg_addr->addr_scan_ctrl1 = REG_SCAN_CTRL_ADDR + 4;
		p_reg_cfg_addr->addr_scan_ctrl2 = REG_SCAN_CTRL_ADDR + 8;
		p_reg_cfg_addr->addr_scan_ctrl3 = REG_SCAN_CTRL_ADDR + 12;
		for (i = 0; i < AW_CHANNEL_NUM_MAX; i++) {
			p_reg_cfg_addr->addr_chl_sel0[i] = REG_CHL_SEL0_ADDR + AFE_CH_ADDR_INTERVAL * i;
			p_reg_cfg_addr->addr_chl_sel1[i] = REG_CHL_SEL1_ADDR + AFE_CH_ADDR_INTERVAL * i;
			p_reg_cfg_addr->addr_touch_th_x[i] = REG_TOUCH_TH_X_ADDR + CAP_CH_ADDR_INTERVAL * i + CAP_CTRL_BASE_ADDR;
			p_reg_cfg_addr->addr_leave_th_x[i] = REG_TOUCH_TH_Y_ADDR + CAP_CH_ADDR_INTERVAL * i + CAP_CTRL_BASE_ADDR;
			p_reg_cfg_addr->addr_touch_th_y[i] = REG_LEAVE_TH_X_ADDR + CAP_CH_ADDR_INTERVAL * i + CAP_CTRL_BASE_ADDR;
			p_reg_cfg_addr->addr_leave_th_y[i] = REG_LEAVE_TH_Y_ADDR + CAP_CH_ADDR_INTERVAL * i + CAP_CTRL_BASE_ADDR;
			p_reg_cfg_addr->addr_button_cfg0[i] = REG_BTN_CFG0_ADDR + CAP_CH_ADDR_INTERVAL * i + CAP_CTRL_BASE_ADDR;
			p_reg_cfg_addr->addr_button_cfg1[i] = REG_BTN_CFG1_ADDR + CAP_CH_ADDR_INTERVAL * i + CAP_CTRL_BASE_ADDR;
			p_reg_cfg_addr->addr_longpresss_cfg0[i] = REG_LONGPRESS_CFG0_ADDR + CAP_CH_ADDR_INTERVAL * i + CAP_CTRL_BASE_ADDR;
			p_reg_cfg_addr->addr_longpresss_cfg1[i] = REG_LONGPRESS_CFG1_ADDR + CAP_CH_ADDR_INTERVAL * i + CAP_CTRL_BASE_ADDR;
			p_reg_cfg_addr->addr_pos_cal_x[i] = REG_POS_CALCU_TH_X_ADDR + CAP_CH_ADDR_INTERVAL * i + CAP_CTRL_BASE_ADDR;
			p_reg_cfg_addr->addr_pos_cal_y[i] = REG_POS_CALCU_TH_Y_ADDR + CAP_CH_ADDR_INTERVAL * i + CAP_CTRL_BASE_ADDR;
			p_reg_cfg_addr->addr_sld_cfg[i] = REG_SLD_CFG_ADDR + CAP_CH_ADDR_INTERVAL * i + CAP_CTRL_BASE_ADDR;
			p_reg_cfg_addr->addr_sld_limit_th[i] = REG_SLD_LIMIT_TH_ADDR + CAP_CH_ADDR_INTERVAL * i + CAP_CTRL_BASE_ADDR;
		}
	}
}

static void aw_slider_ch_parse(AW_PARRAM_INIT_CFG *param_init_struct)
{
	AW_U8 i = 0;
	AW_U8 j = 0;
	AW_U8 channel_num = 0;
	AW_SLIDER_CH_S *g_slider_ch_cfg = aw_get_slider_ch_func();

	for (i = 0; i < AW_CHANNEL_NUM_MAX; i++) {
		if ((param_init_struct->widget_cfg[i].widget_type != NO_TYPE) &&
			(param_init_struct->widget_cfg[i].widget_type < WIDGET_MAX)) {
			for (j = 0; j < AW_CHANNEL_NUM_MAX; j++) {
				if ((param_init_struct->widget_cfg[i].x_pad_cs_sel[j] != 0)
					&& (param_init_struct->widget_cfg[i].x_pad_cs_sel[j] < AW_CS_MAX)) {
						g_slider_ch_cfg->slider_cfg[i].slider_en = AW_TRUE;
						g_slider_ch_cfg->slider_cfg[i].cs_num_x++;
						g_slider_ch_cfg->slider_cfg[i].start_ch = channel_num;
				}
				if (param_init_struct->widget_cfg[i].widget_type == TWO_D_SLIDER) {
					if ((param_init_struct->widget_cfg[i].y_pad_cs_sel[j] != 0)
						&& (param_init_struct->widget_cfg[i].y_pad_cs_sel[j] < AW_CS_MAX)) {
						g_slider_ch_cfg->slider_cfg[i].slider_en = AW_TRUE;
						g_slider_ch_cfg->slider_cfg[i].cs_num_y++;
						g_slider_ch_cfg->slider_cfg[i].start_ch = channel_num;
					}
				}
			}
			channel_num += (g_slider_ch_cfg->slider_cfg[i].cs_num_x + g_slider_ch_cfg->slider_cfg[i].cs_num_y);
		}
	}
}

static void aw_cs_channel_parse(AW_PARRAM_INIT_CFG *param_init_struct)
{
	AW_U8 i = 0;
	AW_U8 j = 0;
	AW_U8 k = 0;
	AW_CS_CH_S *p_cs_ch_s = aw_get_cs_ch_func();

	for (i = 0; i < AW_CHANNEL_NUM_MAX; i++) {
		if ((param_init_struct->widget_cfg[i].widget_type != NO_TYPE) &&
			(param_init_struct->widget_cfg[i].widget_type < WIDGET_MAX)) {
			if (param_init_struct->widget_cfg[i].widget_type == CV_FORCE) {
			} else {
				for (j = 0; j < AW_CHANNEL_NUM_MAX; j++) {
					if ((param_init_struct->widget_cfg[i].x_pad_cs_sel[j] != 0)
						&& (param_init_struct->widget_cfg[i].x_pad_cs_sel[j] < AW_CS_MAX)) {
							p_cs_ch_s->cs_select[k].ch_en = CH_EN;
							p_cs_ch_s->cs_select[k].ch_type = param_init_struct->widget_cfg[i].widget_type;
							p_cs_ch_s->cs_select[k].ch_num = k;
							p_cs_ch_s->cs_select[k].cs_num++;
							if (param_init_struct->widget_cfg[i].widget_type != CV_FORCE)
								p_cs_ch_s->cs_select[k].cs_pin[0] = param_init_struct->widget_cfg[i].x_pad_cs_sel[j];
							k += 1;
						}
					}
					for (j = 0; j < AW_CHANNEL_NUM_MAX; j++) {
					if (param_init_struct->widget_cfg[i].widget_type == TWO_D_SLIDER) {
						if ((param_init_struct->widget_cfg[i].y_pad_cs_sel[j] != 0) &&
							(param_init_struct->widget_cfg[i].y_pad_cs_sel[j] < AW_CS_MAX)) {
								p_cs_ch_s->cs_select[k].ch_en = CH_EN;
								p_cs_ch_s->cs_select[k].ch_type = param_init_struct->widget_cfg[i].widget_type;
								p_cs_ch_s->cs_select[k].ch_num = k;
								p_cs_ch_s->cs_select[k].cs_num++;
							if (param_init_struct->widget_cfg[i].widget_type != CV_FORCE)
								p_cs_ch_s->cs_select[k].cs_pin[0] = param_init_struct->widget_cfg[i].y_pad_cs_sel[j];
							k += 1;
						}
					}
				}
			}
		}
	}
}

static void aw_param_init(AW_PARRAM_INIT_CFG *param_init_struct)
{
	AW_U8 i = 0;
	AW_U8 j = 0;
	REG_CFG_STRUCT reg_cfg_struct;

	AW_CS_CH_S *p_cs_ch_s = aw_get_cs_ch_func();
	AW_SLIDER_CH_S *p_slider_ch_cfg = aw_get_slider_ch_func();

	memset(&reg_cfg_struct, 0, sizeof(REG_CFG_STRUCT));
	// reg_scan_ctrl0
	reg_cfg_struct.reg_scan_ctrl0.field_scan_period = param_init_struct->scan_period;
	// cs ch parse
	aw_cs_channel_parse(param_init_struct);
	// slider start channel parse
	aw_slider_ch_parse(param_init_struct);
	if ((p_cs_ch_s == NULL) || (p_slider_ch_cfg == NULL)) {
		// log show
		return;
	}
	for (i = 0; i < AW_CHANNEL_NUM_MAX; i++) {
		reg_cfg_struct.reg_scan_ctrl0.field_chen_ch[i] = p_cs_ch_s->cs_select[i].ch_en;
		for (j = 0; j < AW_CHANNEL_NUM_MAX; j++)
			reg_cfg_struct.reg_chl_sel0[i].field_cs_sel[j] = p_cs_ch_s->cs_select[i].cs_pin[j];
		// reg_touch_th_x
		reg_cfg_struct.reg_touch_th_x[i].field_touch_th_x = param_init_struct->widget_cfg[i].x_touch_TH;
		// reg_leave_th_x
		reg_cfg_struct.reg_leave_th_x[i].field_leave_th_x = DEFAULT_REG_LEAVE_TH_X;
		// reg_touch_th_y
		reg_cfg_struct.reg_touch_th_y[i].field_touch_th_y = param_init_struct->widget_cfg[i].y_touch_TH;
		// reg_leave_th_y
		reg_cfg_struct.reg_leave_th_y[i].field_leave_th_y = DEFAULT_REG_LEAVE_TH_Y;
		// reg_button_cfg0
		reg_cfg_struct.reg_button_cfg0[i].field_ctl_func = (1 << (param_init_struct->widget_cfg[i].widget_type - 1));
		reg_cfg_struct.reg_button_cfg0[i].field_touch_deb_th = DEFAULT_FIELD_TOUCH_DEB_TH;
		reg_cfg_struct.reg_button_cfg0[i].field_ch_num_y = p_slider_ch_cfg->slider_cfg[i].cs_num_y;
		reg_cfg_struct.reg_button_cfg0[i].field_ch_num_x = p_slider_ch_cfg->slider_cfg[i].cs_num_x;
		reg_cfg_struct.reg_button_cfg0[i].field_start_index = p_slider_ch_cfg->slider_cfg[i].start_ch; // parse start channel
		// reg_button_cfg1
		reg_cfg_struct.reg_button_cfg1[i].field_touch_time_period = param_init_struct->scan_period;
		reg_cfg_struct.reg_button_cfg1[i].field_click_interval = param_init_struct->widget_cfg[i].click_interval;
		// reg_longpresss_cfg0
		reg_cfg_struct.reg_longpresss_cfg0[i].field_longpress_th1 = param_init_struct->widget_cfg[i].long_press_TH1;
		reg_cfg_struct.reg_longpresss_cfg0[i].field_longpress_th2 = param_init_struct->widget_cfg[i].long_press_TH2;
		reg_cfg_struct.reg_longpresss_cfg1[i].field_longpress_th3 = param_init_struct->widget_cfg[i].long_press_TH3;
		// reg_pos_cal_x
		reg_cfg_struct.reg_pos_cal_x[i].field_pos_cal_th_x = param_init_struct->widget_cfg[i].x_pos_calu_TH;
		// reg_pos_cal_y
		reg_cfg_struct.reg_pos_cal_y[i].field_pos_cal_th_y = param_init_struct->widget_cfg[i].y_pos_calu_TH;
		// reg_sld_cfg
		reg_cfg_struct.reg_sld_cfg[i].field_move_recip_th = DEFAULT_FIELD_MOVE_RECIP_TH;
		reg_cfg_struct.reg_sld_cfg[i].field_spe_linear_en = DEFAULT_FIELD_SPE_LINEAR_EN;
		reg_cfg_struct.reg_sld_cfg[i].field_con_sld_en = DEFAULT_FIELD_CON_SLD_EN;
		reg_cfg_struct.reg_sld_cfg[i].field_con_sld_mode = DEFAULT_FIELD_CON_SLD_MODE;
		reg_cfg_struct.reg_sld_cfg[i].field_sld_type = (param_init_struct->widget_cfg[i].widget_type - 1);
		// reg_sld_limit_th
		reg_cfg_struct.reg_sld_limit_th[i].field_sld_limit_th_x = param_init_struct->widget_cfg[i].x_Mini_distance_TH;
		reg_cfg_struct.reg_sld_limit_th[i].field_sld_limit_th_y = param_init_struct->widget_cfg[i].y_Mini_distance_TH;
	}
	aw_reg_addr_cfg();
	aw_reg_data_cfg(&reg_cfg_struct);
	aw_reg_addr_data_cfg();
}

/**
 * @brief this func is generated automatically, do not modify this function!!
 *
 */
void aw_widget_cfg(void)
{
	AW_PARRAM_INIT_CFG slider_init_structure = {0};

	slider_init_structure.scan_period = MS_20;

	slider_init_structure.widget_cfg[0].widget_type = BUTTON;
	slider_init_structure.widget_cfg[0].x_pad_cs_sel[0] = AW_CS11;
	slider_init_structure.widget_cfg[0].x_touch_TH = 50000;
	slider_init_structure.widget_cfg[0].click_interval = 500;
	slider_init_structure.widget_cfg[0].long_press_TH1 = 2000;
	slider_init_structure.widget_cfg[0].long_press_TH2 = 3000;
	slider_init_structure.widget_cfg[0].long_press_TH3 = 4000;

	slider_init_structure.widget_cfg[1].widget_type = ONE_D_SLIDER;
	slider_init_structure.widget_cfg[1].x_pad_cs_sel[0] = AW_CS0;
	slider_init_structure.widget_cfg[1].x_pad_cs_sel[1] = AW_CS10;
	slider_init_structure.widget_cfg[1].x_pad_cs_sel[2] = AW_CS3;
	slider_init_structure.widget_cfg[1].x_pad_cs_sel[3] = AW_CS4;
	slider_init_structure.widget_cfg[1].x_touch_TH = 100000;
	slider_init_structure.widget_cfg[1].x_pos_calu_TH = 100000;
	slider_init_structure.widget_cfg[1].x_Mini_distance_TH = 80;
	slider_init_structure.widget_cfg[1].click_interval = 500;
	slider_init_structure.widget_cfg[1].long_press_TH1 = 2000;
	slider_init_structure.widget_cfg[1].long_press_TH2 = 3000;
	slider_init_structure.widget_cfg[1].long_press_TH3 = 4000;

	aw_param_init(&slider_init_structure);
}
