/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/
//#if PIN_CONFIG_DEV_BOARD
#if 1
#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif


#define IOPCTL_PIO_FUNC6 0x06u            /*!<@brief Selects pin function 6 */

#define IOPCTL_PIO_FULLDRIVE_EN 0x0100u   /*!<@brief Full drive enable */

#define IOPCTL_PIO_FUNC5 0x05u            /*!<@brief Selects pin function 5 */

#define IOPCTL_PIO_SLEW_RATE_SLOW 0x80u /*!<@brief Slow mode */

#define IOPCTL_PIO_ANAMUX_DI 0x00u        /*!<@brief Analog mux is disabled */
#define IOPCTL_PIO_FULLDRIVE_DI 0x00u     /*!<@brief Normal drive */
#define IOPCTL_PIO_FUNC1 0x01u            /*!<@brief Selects pin function 1 */
#define IOPCTL_PIO_INBUF_DI 0x00u         /*!<@brief Disable input buffer function */
#define IOPCTL_PIO_INBUF_EN 0x40u         /*!<@brief Enables input buffer function */
#define IOPCTL_PIO_INV_DI 0x00u           /*!<@brief Input function is not inverted */
#define IOPCTL_PIO_PSEDRAIN_DI 0x00u      /*!<@brief Pseudo Output Drain is disabled */
#define IOPCTL_PIO_PULLUP_EN 0x20u        /*!<@brief Enable pull-up function */
#define IOPCTL_PIO_PUPD_EN 0x10u          /*!<@brief Enable pull-up / pull-down function */
#define IOPCTL_PIO_SLEW_RATE_NORMAL 0x00u /*!<@brief Normal mode */

#define IOPCTL_PIO_ANAMUX_DI 0x00u        /*!<@brief Analog mux is disabled */
#define IOPCTL_PIO_FULLDRIVE_DI 0x00u     /*!<@brief Normal drive */
#define IOPCTL_PIO_FUNC1 0x01u            /*!<@brief Selects pin function 1 */
#define IOPCTL_PIO_INBUF_DI 0x00u         /*!<@brief Disable input buffer function */
#define IOPCTL_PIO_INBUF_EN 0x40u         /*!<@brief Enables input buffer function */
#define IOPCTL_PIO_INV_DI 0x00u           /*!<@brief Input function is not inverted */
#define IOPCTL_PIO_PSEDRAIN_DI 0x00u      /*!<@brief Pseudo Output Drain is disabled */
#define IOPCTL_PIO_PULLDOWN_EN 0x00u      /*!<@brief Enable pull-down function */
#define IOPCTL_PIO_PULLUP_EN 0x20u        /*!<@brief Enable pull-up function */
#define IOPCTL_PIO_PUPD_DI 0x00u          /*!<@brief Disable pull-up / pull-down function */
#define IOPCTL_PIO_PUPD_EN 0x10u          /*!<@brief Enable pull-up / pull-down function */
#define IOPCTL_PIO_SLEW_RATE_NORMAL 0x00u /*!<@brief Normal mode */

/*! @name I3C0_SCL (coord N17), J18[1]/U8[2]/U17[A6]/SCL_CODEC
  @{ */
/* Routed pin properties */
/*!
 * @brief Peripheral name */
#define BOARD_INITI3CPINS_I3C0_SCL_PERIPHERAL I3C
/*!
 * @brief Signal name */
#define BOARD_INITI3CPINS_I3C0_SCL_SIGNAL SCL
/*!
 * @brief PORT peripheral base pointer */
#define BOARD_INITI3CPINS_I3C0_SCL_PORT 2U
/*!
 * @brief PORT pin number */
#define BOARD_INITI3CPINS_I3C0_SCL_PIN 29U
/*!
 * @brief PORT pin mask */
#define BOARD_INITI3CPINS_I3C0_SCL_PIN_MASK (1U << 29U)
/* @} */

/*! @name I3C0_SDA (coord P16), J18[2]/U8[3]/U17[B6]/SDA_CODEC
  @{ */
/* Routed pin properties */
/*!
 * @brief Peripheral name */
#define BOARD_INITI3CPINS_I3C0_SDA_PERIPHERAL I3C
/*!
 * @brief Signal name */
#define BOARD_INITI3CPINS_I3C0_SDA_SIGNAL SDA
/*!
 * @brief PORT peripheral base pointer */
#define BOARD_INITI3CPINS_I3C0_SDA_PORT 2U
/*!
 * @brief PORT pin number */
#define BOARD_INITI3CPINS_I3C0_SDA_PIN 30U
/*!
 * @brief PORT pin mask */
#define BOARD_INITI3CPINS_I3C0_SDA_PIN_MASK (1U << 30U)
/* @} */

// gill modify to QSPI_A
/*! @name FLEXSPI0A_DATA0 (coord L2), U19[D3]
  @{ */
/* Routed pin properties */
#define BOARD_INITFLEXSPI0APINS_QSPI_A_DATA0_PERIPHERAL FLEXSPI        /*!<@brief Peripheral name */
#define BOARD_INITFLEXSPI0APINS_QSPI_A_DATA0_SIGNAL FLEXSPI_A_DATA0    /*!<@brief Signal name */
#define BOARD_INITFLEXSPI0APINS_QSPI_A_DATA0_PORT 1U                   /*!<@brief PORT peripheral base pointer */
#define BOARD_INITFLEXSPI0APINS_QSPI_A_DATA0_PIN 20U                   /*!<@brief PORT pin number */
#define BOARD_INITFLEXSPI0APINS_QSPI_A_DATA0_PIN_MASK (1U << 20U)      /*!<@brief PORT pin mask */
                                                                       /* @} */

/*! @name FLEXSPI0A_DATA1 (coord M2), U19[D2]
  @{ */
/* Routed pin properties */
#define BOARD_INITFLEXSPI0APINS_QSPI_A_DATA1_PERIPHERAL FLEXSPI        /*!<@brief Peripheral name */
#define BOARD_INITFLEXSPI0APINS_QSPI_A_DATA1_SIGNAL FLEXSPI_A_DATA1    /*!<@brief Signal name */
#define BOARD_INITFLEXSPI0APINS_QSPI_A_DATA1_PORT 1U                   /*!<@brief PORT peripheral base pointer */
#define BOARD_INITFLEXSPI0APINS_QSPI_A_DATA1_PIN 21U                   /*!<@brief PORT pin number */
#define BOARD_INITFLEXSPI0APINS_QSPI_A_DATA1_PIN_MASK (1U << 21U)      /*!<@brief PORT pin mask */
                                                                       /* @} */

/*! @name FLEXSPI0A_DATA2 (coord N1), U19[C4]
  @{ */
/* Routed pin properties */
#define BOARD_INITFLEXSPI0APINS_QSPI_A_DATA2_PERIPHERAL FLEXSPI        /*!<@brief Peripheral name */
#define BOARD_INITFLEXSPI0APINS_QSPI_A_DATA2_SIGNAL FLEXSPI_A_DATA2    /*!<@brief Signal name */
#define BOARD_INITFLEXSPI0APINS_QSPI_A_DATA2_PORT 1U                   /*!<@brief PORT peripheral base pointer */
#define BOARD_INITFLEXSPI0APINS_QSPI_A_DATA2_PIN 22U                   /*!<@brief PORT pin number */
#define BOARD_INITFLEXSPI0APINS_QSPI_A_DATA2_PIN_MASK (1U << 22U)      /*!<@brief PORT pin mask */
                                                                       /* @} */

/*! @name FLEXSPI0A_DATA3 (coord N2), U19[D4]
  @{ */
/* Routed pin properties */
#define BOARD_INITFLEXSPI0APINS_QSPI_A_DATA3_PERIPHERAL FLEXSPI        /*!<@brief Peripheral name */
#define BOARD_INITFLEXSPI0APINS_QSPI_A_DATA3_SIGNAL FLEXSPI_A_DATA3    /*!<@brief Signal name */
#define BOARD_INITFLEXSPI0APINS_QSPI_A_DATA3_PORT 1U                   /*!<@brief PORT peripheral base pointer */
#define BOARD_INITFLEXSPI0APINS_QSPI_A_DATA3_PIN 23U                   /*!<@brief PORT pin number */
#define BOARD_INITFLEXSPI0APINS_QSPI_A_DATA3_PIN_MASK (1U << 23U)      /*!<@brief PORT pin mask */
                                                                       /* @} */

/*! @name FLEXSPI0A_SCLK (coord U3), U19[B2]
  @{ */
/* Routed pin properties */
#define BOARD_INITFLEXSPI0APINS_QSPI_A_SCK_PERIPHERAL FLEXSPI        /*!<@brief Peripheral name */
#define BOARD_INITFLEXSPI0APINS_QSPI_A_SCK_SIGNAL FLEXSPI_A_SCLK     /*!<@brief Signal name */
#define BOARD_INITFLEXSPI0APINS_QSPI_A_SCK_PORT 1U                   /*!<@brief PORT peripheral base pointer */
#define BOARD_INITFLEXSPI0APINS_QSPI_A_SCK_PIN 18U                  /*!<@brief PORT pin number */
#define BOARD_INITFLEXSPI0APINS_QSPI_A_SCK_PIN_MASK (1U << 18U)      /*!<@brief PORT pin mask */
                                                                     /* @} */

/*! @name FLEXSPI0A_SS0_N (coord T2), U19[C2]
  @{ */
/* Routed pin properties */
#define BOARD_INITFLEXSPIFLASHPINS_QSPI_A_CS0_PERIPHERAL FLEXSPI	/*!* @brief Peripheral name */
#define BOARD_INITFLEXSPIFLASHPINS_QSPI_A_CS0_SIGNAL FLEXSPI_A_SS0_A	/*!* @brief Signal name */
#define BOARD_INITFLEXSPIFLASHPINS_QSPI_A_CS0_PORT 1U	/*!* @brief PORT peripheral base pointer */
#define BOARD_INITFLEXSPIFLASHPINS_QSPI_A_CS0_PIN 19U	/*!* @brief PORT pin number */
#define BOARD_INITFLEXSPIFLASHPINS_QSPI_A_CS0_PIN_MASK (1U << 19U)	/*!* @brief PORT pin mask */
/* @} */




/*! @name PIO0_3 (coord H2), J1[3]/J36[4]/J45[58]
  @{ */
/* Routed pin properties */
/*!
 * @brief Peripheral name */
#define BOARD_INITFOURDBGPINS_DbgPin5_PERIPHERAL GPIO
/*!
 * @brief Signal name */
#define BOARD_INITFOURDBGPINS_DbgPin5_SIGNAL PIO0
/*!
 * @brief Signal channel */
#define BOARD_INITFOURDBGPINS_DbgPin5_CHANNEL 3

/* Symbols to be used with GPIO driver */
/*!
 * @brief GPIO peripheral base pointer */
#define BOARD_INITFOURDBGPINS_DbgPin5_GPIO GPIO
/*!
 * @brief GPIO output initial state */
#define BOARD_INITFOURDBGPINS_DbgPin5_INIT_GPIO_VALUE 0U
/*!
 * @brief GPIO pin mask */
#define BOARD_INITFOURDBGPINS_DbgPin5_GPIO_PIN_MASK (1U << 3U)
/*!
 * @brief PORT peripheral base pointer */
#define BOARD_INITFOURDBGPINS_DbgPin5_PORT 0U
/*!
 * @brief PORT pin number */
#define BOARD_INITFOURDBGPINS_DbgPin5_PIN 3U
/*!
 * @brief PORT pin mask */
#define BOARD_INITFOURDBGPINS_DbgPin5_PIN_MASK (1U << 3U)
/* @} */

/*! @name PIO0_4 (coord J1), J1[5]/J45[60]
  @{ */
/* Routed pin properties */
/*!
 * @brief Peripheral name */
#define BOARD_INITFOURDBGPINS_DbgPin6_PERIPHERAL GPIO
/*!
 * @brief Signal name */
#define BOARD_INITFOURDBGPINS_DbgPin6_SIGNAL PIO0
/*!
 * @brief Signal channel */
#define BOARD_INITFOURDBGPINS_DbgPin6_CHANNEL 4

/* Symbols to be used with GPIO driver */
/*!
 * @brief GPIO peripheral base pointer */
#define BOARD_INITFOURDBGPINS_DbgPin6_GPIO GPIO
/*!
 * @brief GPIO output initial state */
#define BOARD_INITFOURDBGPINS_DbgPin6_INIT_GPIO_VALUE 0U
/*!
 * @brief GPIO pin mask */
#define BOARD_INITFOURDBGPINS_DbgPin6_GPIO_PIN_MASK (1U << 4U)
/*!
 * @brief PORT peripheral base pointer */
#define BOARD_INITFOURDBGPINS_DbgPin6_PORT 0U
/*!
 * @brief PORT pin number */
#define BOARD_INITFOURDBGPINS_DbgPin6_PIN 4U
/*!
 * @brief PORT pin mask */
#define BOARD_INITFOURDBGPINS_DbgPin6_PIN_MASK (1U << 4U)
/* @} */

/*! @name PIO0_19 (coord A1), J30[3]
  @{ */
/* Routed pin properties */
/*!
 * @brief Peripheral name */
#define BOARD_INITFOURDBGPINS_DbgPin7_PERIPHERAL GPIO
/*!
 * @brief Signal name */
#define BOARD_INITFOURDBGPINS_DbgPin7_SIGNAL PIO0
/*!
 * @brief Signal channel */
#define BOARD_INITFOURDBGPINS_DbgPin7_CHANNEL 19

/* Symbols to be used with GPIO driver */
/*!
 * @brief GPIO peripheral base pointer */
#define BOARD_INITFOURDBGPINS_DbgPin7_GPIO GPIO
/*!
 * @brief GPIO output initial state */
#define BOARD_INITFOURDBGPINS_DbgPin7_INIT_GPIO_VALUE 0U
/*!
 * @brief GPIO pin mask */
#define BOARD_INITFOURDBGPINS_DbgPin7_GPIO_PIN_MASK (1U << 19U)
/*!
 * @brief PORT peripheral base pointer */
#define BOARD_INITFOURDBGPINS_DbgPin7_PORT 0U
/*!
 * @brief PORT pin number */
#define BOARD_INITFOURDBGPINS_DbgPin7_PIN 19U
/*!
 * @brief PORT pin mask */
#define BOARD_INITFOURDBGPINS_DbgPin7_PIN_MASK (1U << 19U)
/* @} */

/*! @name PIO0_20 (coord B2), J30[4]
  @{ */
/* Routed pin properties */
/*!
 * @brief Peripheral name */
#define BOARD_INITFOURDBGPINS_DbgPin8_PERIPHERAL GPIO
/*!
 * @brief Signal name */
#define BOARD_INITFOURDBGPINS_DbgPin8_SIGNAL PIO0
/*!
 * @brief Signal channel */
#define BOARD_INITFOURDBGPINS_DbgPin8_CHANNEL 20

/* Symbols to be used with GPIO driver */
/*!
 * @brief GPIO peripheral base pointer */
#define BOARD_INITFOURDBGPINS_DbgPin8_GPIO GPIO
/*!
 * @brief GPIO output initial state */
#define BOARD_INITFOURDBGPINS_DbgPin8_INIT_GPIO_VALUE 0U
/*!
 * @brief GPIO pin mask */
#define BOARD_INITFOURDBGPINS_DbgPin8_GPIO_PIN_MASK (1U << 20U)
/*!
 * @brief PORT peripheral base pointer */
#define BOARD_INITFOURDBGPINS_DbgPin8_PORT 0U
/*!
 * @brief PORT pin number */
#define BOARD_INITFOURDBGPINS_DbgPin8_PIN 20U
/*!
 * @brief PORT pin mask */
#define BOARD_INITFOURDBGPINS_DbgPin8_PIN_MASK (1U << 20U)
/* @} */


/*!
 * @brief Calls initialization functions.
 *
 */

void dev_BOARD_InitBootPins(void);
void dev_BOARD_InitUSBPins(void); /* Function assigned for the Cortex-M33 */
void dev_BOARD_InitLEDsPins(void); /* Function assigned for the Cortex-M33 */
void dev_BOARD_InitDmicPins(void); /* Function assigned for the Cortex-M33 */
void dev_BOARD_InitAMP_Pins(void);
void dev_BOARD_InitBUTTONsPins(void); /* Function assigned for the Cortex-M33 */
void dev_BOARD_InitI3CPins(void); /* Function assigned for the Cortex-M33 */
void dev_BOARD_InitBTUARTPins(void); /* Function assigned for the Cortex-M33 */
void dev_BOARD_InitAMP_Pins(void); /* Function assigned for the Cortex-M33 */
void dev_BOARD_InitFourDbgPins(void); /* Function assigned for the Cortex-M33 */
void dev_BOARD_InitFlexSPI0APins(void); /* Function assigned for the Cortex-M33 */
void dev_BOARD_InitBTScoPins(void); /* Function assigned for the Cortex-M33 */

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */
#endif
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
