/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v17.0
processor: MIMXRT685S
package_id: MIMXRT685SFVKB
mcu_data: ksdk2_0
processor_version: 24.12.10
board: MIMXRT685-EVK
external_user_signals: {}
pin_labels:
- {pin_num: H2, pin_signal: PIO0_3/FC0_CTS_SDA_SSEL0/CTIMER0_MAT3/FC1_SSEL2/SEC_PIO0_3, label: 'J1[3]/J36[4]/J45[58]', identifier: DbgPin5}
- {pin_num: J1, pin_signal: PIO0_4/FC0_RTS_SCL_SSEL1/CTIMER_INP0/FC1_SSEL3/CMP0_OUT/SEC_PIO0_4, label: 'J1[5]/J45[60]', identifier: DbgPin6}
- {pin_num: A1, pin_signal: PIO0_19/FC2_SSEL2/SCT0_GPI4/SCT0_OUT4/CTIMER_INP5/UTICK_CAP0/SEC_PIO0_19/ADC0_2, label: 'J30[3]', identifier: DbgPin7}
- {pin_num: B2, pin_signal: PIO0_20/FC2_SSEL3/SCT0_GPI5/SCT0_OUT5/CTIMER0_MAT2/CTIMER_INP11/SEC_PIO0_20/ADC0_10, label: 'J30[4]', identifier: DbgPin8}
- {pin_num: B1, pin_signal: PIO1_9/FC5_SSEL3/SCT0_GPI7/UTICK_CAP1/CTIMER1_MAT3/ADC0_12, label: 'J28[1]', identifier: TEST}
- {pin_num: R3, pin_signal: PIO2_21/PDM_DATA23/CTIMER_INP14/FLEXSPI0B_SS1_N, label: 'J31[6]', identifier: PDM_DATA23}
- {pin_num: P3, pin_signal: PIO2_22/PDM_DATA45/FLEXSPI0B_DATA6, label: 'U19[E2]', identifier: QSPI_B_DATA6;PDM_DATA45}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "fsl_gpio.h"
#include "fsl_iopctl.h"
#include "pin_mux_dev.h"
#include "qar87_config.h"

#if PIN_CONFIG_DEV_BOARD

void BOARD_InitPins(void)
{

    const uint32_t fc15_i2c_scl_config = (/* Pin is configured as I2C_SCL */
                                          IOPCTL_PIO_FUNC0 |
                                          /* Enable pull-up / pull-down function */
                                          IOPCTL_PIO_PUPD_EN |
                                          /* Enable pull-up function */
                                          IOPCTL_PIO_PULLUP_EN |
                                          /* Enables input buffer function */
                                          IOPCTL_PIO_INBUF_EN |
                                          /* Normal mode */
                                          IOPCTL_PIO_SLEW_RATE_NORMAL |
                                          /* Normal drive */
                                          IOPCTL_PIO_FULLDRIVE_DI |
                                          /* Analog mux is disabled */
                                          IOPCTL_PIO_ANAMUX_DI |
                                          /* Pseudo Output Drain is enabled */
                                          IOPCTL_PIO_PSEDRAIN_EN |
                                          /* Input function is not inverted */
                                          IOPCTL_PIO_INV_DI);
    /* FC15_SCL PIN (coords: E16) is configured as I2C SCL */
    IOPCTL->FC15_I2C_SCL = fc15_i2c_scl_config;

    const uint32_t fc15_i2c_sda_config = (/* Pin is configured as I2C_SDA */
                                          IOPCTL_PIO_FUNC0 |
                                          /* Enable pull-up / pull-down function */
                                          IOPCTL_PIO_PUPD_EN |
                                          /* Enable pull-up function */
                                          IOPCTL_PIO_PULLUP_EN |
                                          /* Enables input buffer function */
                                          IOPCTL_PIO_INBUF_EN |
                                          /* Normal mode */
                                          IOPCTL_PIO_SLEW_RATE_NORMAL |
                                          /* Normal drive */
                                          IOPCTL_PIO_FULLDRIVE_DI |
                                          /* Analog mux is disabled */
                                          IOPCTL_PIO_ANAMUX_DI |
                                          /* Pseudo Output Drain is enabled */
                                          IOPCTL_PIO_PSEDRAIN_EN |
                                          /* Input function is not inverted */
                                          IOPCTL_PIO_INV_DI);
    /* FC15_SDA PIN (coords: F16) is configured as I2C SDA */
    IOPCTL->FC15_I2C_SDA = fc15_i2c_sda_config;

    const uint32_t port0_pin0_config = (/* Pin is configured as PIO0_0 */
                                        IOPCTL_PIO_FUNC0 |
                                        /* Disable pull-up / pull-down function */
                                        IOPCTL_PIO_PUPD_DI |
                                        /* Enable pull-down function */
                                        IOPCTL_PIO_PULLDOWN_EN |
                                        /* Disable input buffer function */
                                        IOPCTL_PIO_INBUF_DI |
                                        /* Normal mode */
                                        IOPCTL_PIO_SLEW_RATE_NORMAL |
                                        /* Normal drive */
                                        IOPCTL_PIO_FULLDRIVE_DI |
                                        /* Analog mux is disabled */
                                        IOPCTL_PIO_ANAMUX_DI |
                                        /* Pseudo Output Drain is disabled */
                                        IOPCTL_PIO_PSEDRAIN_DI |
                                        /* Input function is not inverted */
                                        IOPCTL_PIO_INV_DI);
    /* PORT0 PIN0 (coords: G1) is configured as PIO0_0 */
    IOPCTL_PinMuxSet(IOPCTL, 0U, 0U, port0_pin0_config);

    const uint32_t port0_pin22_config = (/* Pin is configured as FC3_TXD_SCL_MISO_WS */
                                         IOPCTL_PIO_FUNC1 |
                                         /* Disable pull-up / pull-down function */
                                         IOPCTL_PIO_PUPD_DI |
                                         /* Enable pull-down function */
                                         IOPCTL_PIO_PULLDOWN_EN |
                                         /* Disable input buffer function */
                                         IOPCTL_PIO_INBUF_DI |
                                         /* Normal mode */
                                         IOPCTL_PIO_SLEW_RATE_NORMAL |
                                         /* Normal drive */
                                         IOPCTL_PIO_FULLDRIVE_DI |
                                         /* Analog mux is disabled */
                                         IOPCTL_PIO_ANAMUX_DI |
                                         /* Pseudo Output Drain is disabled */
                                         IOPCTL_PIO_PSEDRAIN_DI |
                                         /* Input function is not inverted */
                                         IOPCTL_PIO_INV_DI);
    /* PORT0 PIN22 (coords: D8) is configured as FC3_TXD_SCL_MISO_WS */
    IOPCTL_PinMuxSet(IOPCTL, 0U, 22U, port0_pin22_config);

    const uint32_t port0_pin28_config = (/* Pin is configured as PIO0_28 */
                                         IOPCTL_PIO_FUNC0 |
                                         /* Disable pull-up / pull-down function */
                                         IOPCTL_PIO_PUPD_DI |
                                         /* Enable pull-down function */
                                         IOPCTL_PIO_PULLDOWN_EN |
                                         /* Enables input buffer function */
                                         IOPCTL_PIO_INBUF_EN |
                                         /* Normal mode */
                                         IOPCTL_PIO_SLEW_RATE_NORMAL |
                                         /* Normal drive */
                                         IOPCTL_PIO_FULLDRIVE_DI |
                                         /* Analog mux is disabled */
                                         IOPCTL_PIO_ANAMUX_DI |
                                         /* Pseudo Output Drain is disabled */
                                         IOPCTL_PIO_PSEDRAIN_DI |
                                         /* Input function is not inverted */
                                         IOPCTL_PIO_INV_DI);
    /* PORT0 PIN28 (coords: D11) is configured as PIO0_28 */
    IOPCTL_PinMuxSet(IOPCTL, 0U, 28U, port0_pin28_config);

    const uint32_t port0_pin29_config = (/* Pin is configured as PIO0_29 */
                                         IOPCTL_PIO_FUNC0 |
                                         /* Disable pull-up / pull-down function */
                                         IOPCTL_PIO_PUPD_DI |
                                         /* Enable pull-down function */
                                         IOPCTL_PIO_PULLDOWN_EN |
                                         /* Enables input buffer function */
                                         IOPCTL_PIO_INBUF_EN |
                                         /* Normal mode */
                                         IOPCTL_PIO_SLEW_RATE_NORMAL |
                                         /* Normal drive */
                                         IOPCTL_PIO_FULLDRIVE_DI |
                                         /* Analog mux is disabled */
                                         IOPCTL_PIO_ANAMUX_DI |
                                         /* Pseudo Output Drain is disabled */
                                         IOPCTL_PIO_PSEDRAIN_DI |
                                         /* Input function is not inverted */
                                         IOPCTL_PIO_INV_DI);
    /* PORT0 PIN29 (coords: B10) is configured as PIO0_29 */
    IOPCTL_PinMuxSet(IOPCTL, 0U, 29U, port0_pin29_config);

    const uint32_t port0_pin6_config = (/* Pin is configured as PIO0_6 */
                                        IOPCTL_PIO_FUNC0 |
                                        /* Disable pull-up / pull-down function */
                                        IOPCTL_PIO_PUPD_DI |
                                        /* Enable pull-down function */
                                        IOPCTL_PIO_PULLDOWN_EN |
                                        /* Enables input buffer function */
                                        IOPCTL_PIO_INBUF_EN |
                                        /* Normal mode */
                                        IOPCTL_PIO_SLEW_RATE_NORMAL |
                                        /* Normal drive */
                                        IOPCTL_PIO_FULLDRIVE_DI |
                                        /* Analog mux is disabled */
                                        IOPCTL_PIO_ANAMUX_DI |
                                        /* Pseudo Output Drain is disabled */
                                        IOPCTL_PIO_PSEDRAIN_DI |
                                        /* Input function is not inverted */
                                        IOPCTL_PIO_INV_DI);
    /* PORT0 PIN6 (coords: E1) is configured as PIO0_6 */
    IOPCTL_PinMuxSet(IOPCTL, 0U, 6U, port0_pin6_config);

    const uint32_t port1_pin15_config = (/* Pin is configured as PIO1_15 */
                                         IOPCTL_PIO_FUNC0 |
                                         /* Disable pull-up / pull-down function */
                                         IOPCTL_PIO_PUPD_DI |
                                         /* Enable pull-down function */
                                         IOPCTL_PIO_PULLDOWN_EN |
                                         /* Enables input buffer function */
                                         IOPCTL_PIO_INBUF_EN |
                                         /* Normal mode */
                                         IOPCTL_PIO_SLEW_RATE_NORMAL |
                                         /* Normal drive */
                                         IOPCTL_PIO_FULLDRIVE_DI |
                                         /* Analog mux is disabled */
                                         IOPCTL_PIO_ANAMUX_DI |
                                         /* Pseudo Output Drain is disabled */
                                         IOPCTL_PIO_PSEDRAIN_DI |
                                         /* Input function is not inverted */
                                         IOPCTL_PIO_INV_DI);
    /* PORT1 PIN15 (coords: N3) is configured as PIO1_15 */
    IOPCTL_PinMuxSet(IOPCTL, 1U, 15U, port1_pin15_config);

    const uint32_t port1_pin8_config = (/* Pin is configured as PIO1_8 */
                                        IOPCTL_PIO_FUNC0 |
                                        /* Disable pull-up / pull-down function */
                                        IOPCTL_PIO_PUPD_DI |
                                        /* Enable pull-down function */
                                        IOPCTL_PIO_PULLDOWN_EN |
                                        /* Enables input buffer function */
                                        IOPCTL_PIO_INBUF_EN |
                                        /* Normal mode */
                                        IOPCTL_PIO_SLEW_RATE_NORMAL |
                                        /* Normal drive */
                                        IOPCTL_PIO_FULLDRIVE_DI |
                                        /* Analog mux is disabled */
                                        IOPCTL_PIO_ANAMUX_DI |
                                        /* Pseudo Output Drain is disabled */
                                        IOPCTL_PIO_PSEDRAIN_DI |
                                        /* Input function is not inverted */
                                        IOPCTL_PIO_INV_DI);
    /* PORT1 PIN8 (coords: B5) is configured as PIO1_8 */
    IOPCTL_PinMuxSet(IOPCTL, 1U, 8U, port1_pin8_config);
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
PCA9422_I3C:
- options: {callFromInitBoot: 'true', coreID: cm33, enableClock: 'true'}
- pin_list:
  - {pin_num: N17, peripheral: I3C, signal: SCL, pin_signal: PIO2_29/I3C0_SCL/SCT0_OUT0/CLKOUT, ibena: enabled}
  - {pin_num: P16, peripheral: I3C, signal: SDA, pin_signal: PIO2_30/I3C0_SDA/SCT0_OUT3/CLKIN/CMP0_OUT, ibena: enabled}
  - {pin_num: E17, peripheral: GPIO, signal: 'PIO1, 0', pin_signal: PIO1_0/FC4_RTS_SCL_SSEL1/SCT0_GPI1/SCT0_OUT7/CTIMER_INP8/FC3_SSEL3, ibena: enabled}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : PCA9422_I3C
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
/* Function assigned for the Cortex-M33 */
void PCA9422_I3C(void)
{

    const uint32_t port1_pin0_config = (/* Pin is configured as PIO1_0 */
                                        IOPCTL_PIO_FUNC0 |
                                        /* Disable pull-up / pull-down function */
                                        IOPCTL_PIO_PUPD_DI |
                                        /* Enable pull-down function */
                                        IOPCTL_PIO_PULLDOWN_EN |
                                        /* Enables input buffer function */
                                        IOPCTL_PIO_INBUF_EN |
                                        /* Normal mode */
                                        IOPCTL_PIO_SLEW_RATE_NORMAL |
                                        /* Normal drive */
                                        IOPCTL_PIO_FULLDRIVE_DI |
                                        /* Analog mux is disabled */
                                        IOPCTL_PIO_ANAMUX_DI |
                                        /* Pseudo Output Drain is disabled */
                                        IOPCTL_PIO_PSEDRAIN_DI |
                                        /* Input function is not inverted */
                                        IOPCTL_PIO_INV_DI);
    /* PORT1 PIN0 (coords: E17) is configured as PIO1_0 */
    IOPCTL_PinMuxSet(IOPCTL, 1U, 0U, port1_pin0_config);

    const uint32_t I3C_ICM_SCL = (/* Pin is configured as I3C0_SCL */
                                  IOPCTL_PIO_FUNC1 |
                                  /* Disable pull-up / pull-down function */
                                  IOPCTL_PIO_PUPD_DI |
                                  /* Enable pull-down function */
                                  IOPCTL_PIO_PULLDOWN_EN |
                                  /* Enables input buffer function */
                                  IOPCTL_PIO_INBUF_EN |
                                  /* Normal mode */
                                  IOPCTL_PIO_SLEW_RATE_NORMAL |
                                  /* Normal drive */
                                  IOPCTL_PIO_FULLDRIVE_DI |
                                  /* Analog mux is disabled */
                                  IOPCTL_PIO_ANAMUX_DI |
                                  /* Pseudo Output Drain is disabled */
                                  IOPCTL_PIO_PSEDRAIN_DI |
                                  /* Input function is not inverted */
                                  IOPCTL_PIO_INV_DI);
    /* PORT2 PIN29 (coords: N17) is configured as I3C0_SCL */
    IOPCTL_PinMuxSet(IOPCTL, PCA9422_I3C_I3C_ICM_SCL_PORT, PCA9422_I3C_I3C_ICM_SCL_PIN, I3C_ICM_SCL);

    const uint32_t I3C_ICM_SDA = (/* Pin is configured as I3C0_SDA */
                                  IOPCTL_PIO_FUNC1 |
                                  /* Disable pull-up / pull-down function */
                                  IOPCTL_PIO_PUPD_DI |
                                  /* Enable pull-down function */
                                  IOPCTL_PIO_PULLDOWN_EN |
                                  /* Enables input buffer function */
                                  IOPCTL_PIO_INBUF_EN |
                                  /* Normal mode */
                                  IOPCTL_PIO_SLEW_RATE_NORMAL |
                                  /* Normal drive */
                                  IOPCTL_PIO_FULLDRIVE_DI |
                                  /* Analog mux is disabled */
                                  IOPCTL_PIO_ANAMUX_DI |
                                  /* Pseudo Output Drain is disabled */
                                  IOPCTL_PIO_PSEDRAIN_DI |
                                  /* Input function is not inverted */
                                  IOPCTL_PIO_INV_DI);
    /* PORT2 PIN30 (coords: P16) is configured as I3C0_SDA */
    IOPCTL_PinMuxSet(IOPCTL, PCA9422_I3C_I3C_ICM_SDA_PORT, PCA9422_I3C_I3C_ICM_SDA_PIN, I3C_ICM_SDA);
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
AMP_I2S:
- options: {callFromInitBoot: 'true', coreID: cm33, enableClock: 'true'}
- pin_list:
  - {pin_num: L3, peripheral: FLEXCOMM1, signal: RXD_SDA_MOSI_DATA, pin_signal: PIO0_9/FC1_RXD_SDA_MOSI_DATA/SCT0_GPI6/SCT0_OUT6/CTIMER1_MAT2/I2S_BRIDGE_DATA_OUT/SEC_PIO0_9,
    ibena: enabled, drive: full}
  - {pin_num: J2, peripheral: FLEXCOMM1, signal: SCK, pin_signal: PIO0_7/FC1_SCK/SCT0_GPI4/SCT0_OUT4/CTIMER1_MAT0/I2S_BRIDGE_CLK_OUT/SEC_PIO0_7, ibena: enabled, drive: full}
  - {pin_num: K4, peripheral: FLEXCOMM1, signal: TXD_SCL_MISO_WS, pin_signal: PIO0_8/FC1_TXD_SCL_MISO_WS/SCT0_GPI5/SCT0_OUT5/CTIMER1_MAT1/I2S_BRIDGE_WS_OUT/SEC_PIO0_8,
    ibena: enabled, drive: full}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : AMP_I2S
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
/* Function assigned for the Cortex-M33 */
void AMP_I2S(void)
{

    const uint32_t port0_pin7_config = (/* Pin is configured as FC1_SCK */
                                        IOPCTL_PIO_FUNC1 |
                                        /* Disable pull-up / pull-down function */
                                        IOPCTL_PIO_PUPD_DI |
                                        /* Enable pull-down function */
                                        IOPCTL_PIO_PULLDOWN_EN |
                                        /* Enables input buffer function */
                                        IOPCTL_PIO_INBUF_EN |
                                        /* Normal mode */
                                        IOPCTL_PIO_SLEW_RATE_NORMAL |
                                        /* Full drive enable */
                                        IOPCTL_PIO_FULLDRIVE_EN |
                                        /* Analog mux is disabled */
                                        IOPCTL_PIO_ANAMUX_DI |
                                        /* Pseudo Output Drain is disabled */
                                        IOPCTL_PIO_PSEDRAIN_DI |
                                        /* Input function is not inverted */
                                        IOPCTL_PIO_INV_DI);
    /* PORT0 PIN7 (coords: J2) is configured as FC1_SCK */
    IOPCTL_PinMuxSet(IOPCTL, 0U, 7U, port0_pin7_config);

    const uint32_t port0_pin8_config = (/* Pin is configured as FC1_TXD_SCL_MISO_WS */
                                        IOPCTL_PIO_FUNC1 |
                                        /* Disable pull-up / pull-down function */
                                        IOPCTL_PIO_PUPD_DI |
                                        /* Enable pull-down function */
                                        IOPCTL_PIO_PULLDOWN_EN |
                                        /* Enables input buffer function */
                                        IOPCTL_PIO_INBUF_EN |
                                        /* Normal mode */
                                        IOPCTL_PIO_SLEW_RATE_NORMAL |
                                        /* Full drive enable */
                                        IOPCTL_PIO_FULLDRIVE_EN |
                                        /* Analog mux is disabled */
                                        IOPCTL_PIO_ANAMUX_DI |
                                        /* Pseudo Output Drain is disabled */
                                        IOPCTL_PIO_PSEDRAIN_DI |
                                        /* Input function is not inverted */
                                        IOPCTL_PIO_INV_DI);
    /* PORT0 PIN8 (coords: K4) is configured as FC1_TXD_SCL_MISO_WS */
    IOPCTL_PinMuxSet(IOPCTL, 0U, 8U, port0_pin8_config);

    const uint32_t port0_pin9_config = (/* Pin is configured as FC1_RXD_SDA_MOSI_DATA */
                                        IOPCTL_PIO_FUNC1 |
                                        /* Disable pull-up / pull-down function */
                                        IOPCTL_PIO_PUPD_DI |
                                        /* Enable pull-down function */
                                        IOPCTL_PIO_PULLDOWN_EN |
                                        /* Enables input buffer function */
                                        IOPCTL_PIO_INBUF_EN |
                                        /* Normal mode */
                                        IOPCTL_PIO_SLEW_RATE_NORMAL |
                                        /* Full drive enable */
                                        IOPCTL_PIO_FULLDRIVE_EN |
                                        /* Analog mux is disabled */
                                        IOPCTL_PIO_ANAMUX_DI |
                                        /* Pseudo Output Drain is disabled */
                                        IOPCTL_PIO_PSEDRAIN_DI |
                                        /* Input function is not inverted */
                                        IOPCTL_PIO_INV_DI);
    /* PORT0 PIN9 (coords: L3) is configured as FC1_RXD_SDA_MOSI_DATA */
    IOPCTL_PinMuxSet(IOPCTL, 0U, 9U, port0_pin9_config);
}

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitArduinoUARTPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
/* Function assigned for the Cortex-M33 */
void dev_BOARD_InitBTUARTPins(void)
{
   // gill original FC4 -> FC0
    const uint32_t port0_pin1_config = (/* Pin is configured as FC0_TXD_SCL_MISO_WS */
                                            IOPCTL_PIO_FUNC1 |
                                            /* Disable pull-up / pull-down function */
                                            IOPCTL_PIO_PUPD_DI |
                                            /* Enable pull-down function */
                                            IOPCTL_PIO_PULLDOWN_EN |
                                            /* Disable input buffer function */
                                            IOPCTL_PIO_INBUF_DI |
                                            /* Normal mode */
                                            IOPCTL_PIO_SLEW_RATE_NORMAL |
                                            /* Normal drive */
                                            IOPCTL_PIO_FULLDRIVE_DI |
                                            /* Analog mux is disabled */
                                            IOPCTL_PIO_ANAMUX_DI |
                                            /* Pseudo Output Drain is disabled */
                                            IOPCTL_PIO_PSEDRAIN_DI |
                                            /* Input function is not inverted */
                                            IOPCTL_PIO_INV_DI);
        /* PORT0 PIN1 (coords: G2) is configured as FC0_TXD_SCL_MISO_WS */
        IOPCTL_PinMuxSet(IOPCTL, 0U, 1U, port0_pin1_config);

        const uint32_t port0_pin2_config = (/* Pin is configured as FC0_RXD_SDA_MOSI_DATA */
                                            IOPCTL_PIO_FUNC1 |
                                            /* Disable pull-up / pull-down function */
                                            IOPCTL_PIO_PUPD_DI |
                                            /* Enable pull-down function */
                                            IOPCTL_PIO_PULLDOWN_EN |
                                            /* Enables input buffer function */
                                            IOPCTL_PIO_INBUF_EN |
                                            /* Normal mode */
                                            IOPCTL_PIO_SLEW_RATE_NORMAL |
                                            /* Normal drive */
                                            IOPCTL_PIO_FULLDRIVE_DI |
                                            /* Analog mux is disabled */
                                            IOPCTL_PIO_ANAMUX_DI |
                                            /* Pseudo Output Drain is disabled */
                                            IOPCTL_PIO_PSEDRAIN_DI |
                                            /* Input function is not inverted */
                                            IOPCTL_PIO_INV_DI);
        /* PORT0 PIN2 (coords: G4) is configured as FC0_RXD_SDA_MOSI_DATA */
        IOPCTL_PinMuxSet(IOPCTL, 0U, 2U, port0_pin2_config);

    const uint32_t port0_pin3_config = (/* Pin is configured as FC0_CTS_SDA_SSEL0 */
                                            IOPCTL_PIO_FUNC1 |
                                            /* Disable pull-up / pull-down function */
                                            IOPCTL_PIO_PUPD_DI |
                                            /* Enable pull-down function */
                                            IOPCTL_PIO_PULLDOWN_EN |
                                            /* Disable input buffer function */
                                            IOPCTL_PIO_INBUF_DI |
                                            /* Normal mode */
                                            IOPCTL_PIO_SLEW_RATE_NORMAL |
                                            /* Normal drive */
                                            IOPCTL_PIO_FULLDRIVE_DI |
                                            /* Analog mux is disabled */
                                            IOPCTL_PIO_ANAMUX_DI |
                                            /* Pseudo Output Drain is disabled */
                                            IOPCTL_PIO_PSEDRAIN_DI |
                                            /* Input function is not inverted */
                                            IOPCTL_PIO_INV_DI);
        /* PORT0 PIN3 (coords: H2) is configured as FC0_CTS_SDA_SSEL0 */
        IOPCTL_PinMuxSet(IOPCTL, 0U, 3U, port0_pin3_config);

        const uint32_t port0_pin4_config = (/* Pin is configured as FC0_RTS_SCL_SSEL1 */
                                            IOPCTL_PIO_FUNC1 |
                                            /* Disable pull-up / pull-down function */
                                            IOPCTL_PIO_PUPD_DI |
                                            /* Enable pull-down function */
                                            IOPCTL_PIO_PULLDOWN_EN |
                                            /* Disable input buffer function */
                                            IOPCTL_PIO_INBUF_DI |
                                            /* Normal mode */
                                            IOPCTL_PIO_SLEW_RATE_NORMAL |
                                            /* Normal drive */
                                            IOPCTL_PIO_FULLDRIVE_DI |
                                            /* Analog mux is disabled */
                                            IOPCTL_PIO_ANAMUX_DI |
                                            /* Pseudo Output Drain is disabled */
                                            IOPCTL_PIO_PSEDRAIN_DI |
                                            /* Input function is not inverted */
                                            IOPCTL_PIO_INV_DI);
        /* PORT0 PIN4 (coords: J1) is configured as FC0_RTS_SCL_SSEL1 */
        IOPCTL_PinMuxSet(IOPCTL, 0U, 4U, port0_pin4_config);
}

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitScoPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
/* Function assigned for the Cortex-M33 */
void dev_BOARD_InitBTScoPins(void)
{
    const uint32_t port0_pin14_config = (/* Pin is configured as FC2_SCK */
                                         IOPCTL_PIO_FUNC1 |
                                         /* Disable pull-up / pull-down function */
                                         IOPCTL_PIO_PUPD_DI |
                                         /* Enable pull-down function */
                                         IOPCTL_PIO_PULLDOWN_EN |
                                         /* Disable input buffer function */
                                         IOPCTL_PIO_INBUF_DI |
                                         /* Normal mode */
                                         IOPCTL_PIO_SLEW_RATE_NORMAL |
                                         /* Normal drive */
                                         IOPCTL_PIO_FULLDRIVE_DI |
                                         /* Analog mux is disabled */
                                         IOPCTL_PIO_ANAMUX_DI |
                                         /* Pseudo Output Drain is disabled */
                                         IOPCTL_PIO_PSEDRAIN_DI |
                                         /* Input function is not inverted */
                                         IOPCTL_PIO_INV_DI);
    /* PORT0 PIN14 (coords: K4) is configured as FC2_SCK */
    IOPCTL_PinMuxSet(IOPCTL, 0U, 14U, port0_pin14_config);

    const uint32_t port0_pin15_config = (/* Pin is configured as FC2_TXD_SCL_MISO_WS */
                                         IOPCTL_PIO_FUNC1 |
                                         /* Disable pull-up / pull-down function */
                                         IOPCTL_PIO_PUPD_DI |
                                         /* Enable pull-down function */
                                         IOPCTL_PIO_PULLDOWN_EN |
                                         /* Disable input buffer function */
                                         IOPCTL_PIO_INBUF_DI |
                                         /* Normal mode */
                                         IOPCTL_PIO_SLEW_RATE_NORMAL |
                                         /* Normal drive */
                                         IOPCTL_PIO_FULLDRIVE_DI |
                                         /* Analog mux is disabled */
                                         IOPCTL_PIO_ANAMUX_DI |
                                         /* Pseudo Output Drain is disabled */
                                         IOPCTL_PIO_PSEDRAIN_DI |
                                         /* Input function is not inverted */
                                         IOPCTL_PIO_INV_DI);
    /* PORT0 PIN15 (coords: J6) is configured as FC2_TXD_SCL_MISO_WS */
    IOPCTL_PinMuxSet(IOPCTL, 0U, 15U, port0_pin15_config);

    const uint32_t port0_pin16_config = (/* Pin is configured as FC2_RXD_SDA_MOSI_DATA */
                                         IOPCTL_PIO_FUNC1 |
                                         /* Disable pull-up / pull-down function */
                                         IOPCTL_PIO_PUPD_DI |
                                         /* Enable pull-down function */
                                         IOPCTL_PIO_PULLDOWN_EN |
                                         /* Enables input buffer function */
                                         IOPCTL_PIO_INBUF_EN |
                                         /* Normal mode */
                                         IOPCTL_PIO_SLEW_RATE_NORMAL |
                                         /* Full drive enable */
                                         IOPCTL_PIO_FULLDRIVE_EN |
                                         /* Analog mux is disabled */
                                         IOPCTL_PIO_ANAMUX_DI |
                                         /* Pseudo Output Drain is disabled */
                                         IOPCTL_PIO_PSEDRAIN_DI |
                                         /* Input function is not inverted */
                                         IOPCTL_PIO_INV_DI);
    /* PORT0 PIN16 (coords: K5) is configured as FC2_RXD_SDA_MOSI_DATA */
    IOPCTL_PinMuxSet(IOPCTL, 0U, 16U, port0_pin16_config);

    const uint32_t port0_pin30_config = (/* Pin is configured as FC4_RXD_SDA_MOSI_DATA */
                                             IOPCTL_PIO_FUNC1 |
                                             /* Disable pull-up / pull-down function */
                                             IOPCTL_PIO_PUPD_DI |
                                             /* Enable pull-down function */
                                             IOPCTL_PIO_PULLDOWN_EN |
                                             /* Disable input buffer function */
                                             IOPCTL_PIO_INBUF_DI |
                                             /* Normal mode */
                                             IOPCTL_PIO_SLEW_RATE_NORMAL |
                                             /* Normal drive */
                                             IOPCTL_PIO_FULLDRIVE_DI |
                                             /* Analog mux is disabled */
                                             IOPCTL_PIO_ANAMUX_DI |
                                             /* Pseudo Output Drain is disabled */
                                             IOPCTL_PIO_PSEDRAIN_DI |
                                             /* Input function is not inverted */
                                             IOPCTL_PIO_INV_DI);
        /* PORT0 PIN30 (coords: L8) is configured as FC4_RXD_SDA_MOSI_DATA */
        IOPCTL_PinMuxSet(IOPCTL, 0U, 30U, port0_pin30_config);
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
dev_BOARD_InitDmicPins:
- options: {callFromInitBoot: 'true', coreID: cm33, enableClock: 'true'}
- pin_list:
  - {pin_num: R1, peripheral: DMIC0, signal: 'CLK, 0_1', pin_signal: PIO2_16/PDM_CLK01}
  - {pin_num: U2, peripheral: DMIC0, signal: 'DATA, 0_1', pin_signal: PIO2_20/PDM_DATA01, ibena: enabled}
  - {pin_num: R3, peripheral: DMIC0, signal: 'DATA, 2_3', pin_signal: PIO2_21/PDM_DATA23/CTIMER_INP14/FLEXSPI0B_SS1_N, ibena: enabled}
  - {pin_num: P3, peripheral: DMIC0, signal: 'DATA, 4_5', pin_signal: PIO2_22/PDM_DATA45/FLEXSPI0B_DATA6, identifier: PDM_DATA45, ibena: enabled}
  - {pin_num: P5, peripheral: DMIC0, signal: 'DATA, 6_7', pin_signal: PIO2_23/PDM_DATA67/FLEXSPI0B_DATA7, identifier: PDM_DATA67, ibena: enabled}
  - {pin_num: U1, peripheral: DMIC0, signal: 'CLK, 2_3', pin_signal: PIO2_17/PDM_CLK23/FLEXSPI0B_DATA4, identifier: PDM_CLK23, ibena: disabled}
  - {pin_num: R2, peripheral: DMIC0, signal: 'CLK, 4_5', pin_signal: PIO2_18/PDM_CLK45/FLEXSPI0B_DATA5, identifier: PDM_CLK45}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : dev_BOARD_InitDmicPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
/* Function assigned for the Cortex-M33 */
void dev_BOARD_InitDmicPins(void)
{
    const uint32_t PDM_CLK01 = (/* Pin is configured as PDM_CLK01 */
                                IOPCTL_PIO_FUNC1 |
                                /* Disable pull-up / pull-down function */
                                IOPCTL_PIO_PUPD_DI |
                                /* Enable pull-down function */
                                IOPCTL_PIO_PULLDOWN_EN |
                                /* Disable input buffer function */
                                IOPCTL_PIO_INBUF_DI |
                                /* Normal mode */
                                IOPCTL_PIO_SLEW_RATE_NORMAL |
                                /* Normal drive */
                                IOPCTL_PIO_FULLDRIVE_DI |
                                /* Analog mux is disabled */
                                IOPCTL_PIO_ANAMUX_DI |
                                /* Pseudo Output Drain is disabled */
                                IOPCTL_PIO_PSEDRAIN_DI |
                                /* Input function is not inverted */
                                IOPCTL_PIO_INV_DI);
    /* PORT2 PIN16 (coords: R1) is configured as PDM_CLK01 */
    IOPCTL_PinMuxSet(IOPCTL, BOARD_INITDMICPINS_PDM_CLK01_PORT, BOARD_INITDMICPINS_PDM_CLK01_PIN, PDM_CLK01);
    const uint32_t PDM_CLK23 = (/* Pin is configured as PDM_CLK23 */
                                IOPCTL_PIO_FUNC1 |
                                /* Disable pull-up / pull-down function */
                                IOPCTL_PIO_PUPD_DI |
                                /* Enable pull-down function */
                                IOPCTL_PIO_PULLDOWN_EN |
                                /* Disable input buffer function */
                                IOPCTL_PIO_INBUF_DI |
                                /* Normal mode */
                                IOPCTL_PIO_SLEW_RATE_NORMAL |
                                /* Normal drive */
                                IOPCTL_PIO_FULLDRIVE_DI |
                                /* Analog mux is disabled */
                                IOPCTL_PIO_ANAMUX_DI |
                                /* Pseudo Output Drain is disabled */
                                IOPCTL_PIO_PSEDRAIN_DI |
                                /* Input function is not inverted */
                                IOPCTL_PIO_INV_DI);
    /* PORT2 PIN17 (coords: U1) is configured as PDM_CLK23 */
    IOPCTL_PinMuxSet(IOPCTL, BOARD_INITDMICPINS_PDM_CLK23_PORT, BOARD_INITDMICPINS_PDM_CLK23_PIN, PDM_CLK23);

    const uint32_t PDM_DATA01 = (/* Pin is configured as PDM_DATA01 */
                                 IOPCTL_PIO_FUNC1 |
                                 /* Disable pull-up / pull-down function */
                                 IOPCTL_PIO_PUPD_DI |
                                 /* Enable pull-down function */
                                 IOPCTL_PIO_PULLDOWN_EN |
                                 /* Enables input buffer function */
                                 IOPCTL_PIO_INBUF_EN |
                                 /* Normal mode */
                                 IOPCTL_PIO_SLEW_RATE_NORMAL |
                                 /* Normal drive */
                                 IOPCTL_PIO_FULLDRIVE_DI |
                                 /* Analog mux is disabled */
                                 IOPCTL_PIO_ANAMUX_DI |
                                 /* Pseudo Output Drain is disabled */
                                 IOPCTL_PIO_PSEDRAIN_DI |
                                 /* Input function is not inverted */
                                 IOPCTL_PIO_INV_DI);
    /* PORT2 PIN20 (coords: U2) is configured as PDM_DATA01 */
    IOPCTL_PinMuxSet(IOPCTL, BOARD_INITDMICPINS_PDM_DATA01_PORT, BOARD_INITDMICPINS_PDM_DATA01_PIN, PDM_DATA01);

    const uint32_t PDM_DATA23 = (/* Pin is configured as PDM_DATA23 */
                                 IOPCTL_PIO_FUNC1 |
                                 /* Disable pull-up / pull-down function */
                                 IOPCTL_PIO_PUPD_DI |
                                 /* Enable pull-down function */
                                 IOPCTL_PIO_PULLDOWN_EN |
                                 /* Enables input buffer function */
                                 IOPCTL_PIO_INBUF_EN |
                                 /* Normal mode */
                                 IOPCTL_PIO_SLEW_RATE_NORMAL |
                                 /* Normal drive */
                                 IOPCTL_PIO_FULLDRIVE_DI |
                                 /* Analog mux is disabled */
                                 IOPCTL_PIO_ANAMUX_DI |
                                 /* Pseudo Output Drain is disabled */
                                 IOPCTL_PIO_PSEDRAIN_DI |
                                 /* Input function is not inverted */
                                 IOPCTL_PIO_INV_DI);
    /* PORT2 PIN21 (coords: R3) is configured as PDM_DATA23 */
    IOPCTL_PinMuxSet(IOPCTL, BOARD_INITDMICPINS_PDM_DATA23_PORT, BOARD_INITDMICPINS_PDM_DATA23_PIN, PDM_DATA23);
}

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : dev_BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void dev_BOARD_InitBootPins(void)
{
    BOARD_InitPins();
    PCA9422_I3C();
    AMP_I2S();
    dev_BOARD_InitBTUARTPins();
    dev_BOARD_InitBTScoPins();
    dev_BOARD_InitDmicPins();
    //dev_BOARD_InitFlexSPI0APins();
    // gill to do Need Audio Debug pin init
}

#if 0
/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitFlexSPI0BPins:
- options: {callFromInitBoot: 'true', coreID: cm33, enableClock: 'true'}
- pin_list:
  - {pin_num: L2, peripheral: FLEXSPI, signal: FLEXSPI_B_DATA0, pin_signal: PIO1_11/HS_SPI_SCK/CTIMER2_MAT0/FLEXSPI0B_DATA0, ibena: enabled, drive: full}
  - {pin_num: M2, peripheral: FLEXSPI, signal: FLEXSPI_B_DATA1, pin_signal: PIO1_12/HS_SPI_MISO/CTIMER2_MAT1/FLEXSPI0B_DATA1, ibena: enabled, drive: full}
  - {pin_num: N1, peripheral: FLEXSPI, signal: FLEXSPI_B_DATA2, pin_signal: PIO1_13/HS_SPI_MOSI/CTIMER2_MAT2/FLEXSPI0B_DATA2, ibena: enabled, drive: full}
  - {pin_num: N2, peripheral: FLEXSPI, signal: FLEXSPI_B_DATA3, pin_signal: PIO1_14/HS_SPI_SSEL0/CTIMER2_MAT3/FLEXSPI0B_DATA3, ibena: enabled, drive: full}
  - {pin_num: U3, peripheral: FLEXSPI, signal: FLEXSPI_B_SCLK, pin_signal: PIO1_29/FLEXSPI0A_SS1_N/SCT0_OUT5/UTICK_CAP2/CTIMER_INP13/FLEXSPI0B_SCLK, ibena: enabled,
    drive: full}
  - {pin_num: T3, peripheral: GPIO, signal: 'PIO2, 12', pin_signal: PIO2_12/SCT0_OUT6/CTIMER2_MAT2}
  - {pin_num: T2, peripheral: FLEXSPI, signal: FLEXSPI_B_SS0_B, pin_signal: PIO2_19/PDM_CLK67/FLEXSPI0B_SS0_N}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitFlexSPI0BPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
/* Function assigned for the Cortex-M33 */
void dev_BOARD_InitFlexSPI0APins(void)
{
	// gill psram pin

    const uint32_t QSPI_A_DATA0 = (/* Pin is configured as FLEXSPI0B_DATA0 */
    		IOPCTL_PIO_FUNC1 |
    		                                 /* Disable pull-up / pull-down function */
    		                                 IOPCTL_PIO_PUPD_DI |
    		                                 /* Enable pull-down function */
    		                                 IOPCTL_PIO_PULLDOWN_EN |
    		                                 /* Disable input buffer function */
    		                                 IOPCTL_PIO_INBUF_DI |
    		                                 /* Normal mode */
    		                                 IOPCTL_PIO_SLEW_RATE_NORMAL |
    		                                 /* Normal drive */
    		                                 IOPCTL_PIO_FULLDRIVE_DI |
    		                                 /* Analog mux is disabled */
    		                                 IOPCTL_PIO_ANAMUX_DI |
    		                                 /* Pseudo Output Drain is disabled */
    		                                 IOPCTL_PIO_PSEDRAIN_DI |
    		                                 /* Input function is not inverted */
    		                                 IOPCTL_PIO_INV_DI);
    /* PORT1 PIN11 (coords: L2) is configured as FLEXSPI0B_DATA0 */
    IOPCTL_PinMuxSet(IOPCTL, BOARD_INITFLEXSPI0APINS_QSPI_A_DATA0_PORT, BOARD_INITFLEXSPI0APINS_QSPI_A_DATA0_PIN, QSPI_A_DATA0);

    const uint32_t QSPI_A_DATA1 = (/* Pin is configured as FLEXSPI0B_DATA1 */
    		IOPCTL_PIO_FUNC1 |
    		                                 /* Disable pull-up / pull-down function */
    		                                 IOPCTL_PIO_PUPD_DI |
    		                                 /* Enable pull-down function */
    		                                 IOPCTL_PIO_PULLDOWN_EN |
    		                                 /* Disable input buffer function */
    		                                 IOPCTL_PIO_INBUF_DI |
    		                                 /* Normal mode */
    		                                 IOPCTL_PIO_SLEW_RATE_NORMAL |
    		                                 /* Normal drive */
    		                                 IOPCTL_PIO_FULLDRIVE_DI |
    		                                 /* Analog mux is disabled */
    		                                 IOPCTL_PIO_ANAMUX_DI |
    		                                 /* Pseudo Output Drain is disabled */
    		                                 IOPCTL_PIO_PSEDRAIN_DI |
    		                                 /* Input function is not inverted */
    		                                 IOPCTL_PIO_INV_DI);
    /* PORT1 PIN12 (coords: M2) is configured as FLEXSPI0B_DATA1 */
    IOPCTL_PinMuxSet(IOPCTL, BOARD_INITFLEXSPI0APINS_QSPI_A_DATA1_PORT, BOARD_INITFLEXSPI0APINS_QSPI_A_DATA1_PIN, QSPI_A_DATA1);

    const uint32_t QSPI_A_DATA2 = (/* Pin is configured as FLEXSPI0A_DATA2 */
    		IOPCTL_PIO_FUNC1 |
    		                                 /* Disable pull-up / pull-down function */
    		                                 IOPCTL_PIO_PUPD_DI |
    		                                 /* Enable pull-down function */
    		                                 IOPCTL_PIO_PULLDOWN_EN |
    		                                 /* Enables input buffer function */
    		                                 IOPCTL_PIO_INBUF_EN |
    		                                 /* Normal mode */
    		                                 IOPCTL_PIO_SLEW_RATE_NORMAL |
    		                                 /* Full drive enable */
    		                                 IOPCTL_PIO_FULLDRIVE_EN |
    		                                 /* Analog mux is disabled */
    		                                 IOPCTL_PIO_ANAMUX_DI |
    		                                 /* Pseudo Output Drain is disabled */
    		                                 IOPCTL_PIO_PSEDRAIN_DI |
    		                                 /* Input function is not inverted */
    		                                 IOPCTL_PIO_INV_DI);
    /* PORT1 PIN13 (coords: N1) is configured as FLEXSPI0B_DATA2 */
    IOPCTL_PinMuxSet(IOPCTL, BOARD_INITFLEXSPI0APINS_QSPI_A_DATA2_PORT, BOARD_INITFLEXSPI0APINS_QSPI_A_DATA2_PIN, QSPI_A_DATA2);

    const uint32_t QSPI_A_DATA3 = (/* Pin is configured as FLEXSPI0B_DATA3 */
    		IOPCTL_PIO_FUNC1 |
    		                                 /* Disable pull-up / pull-down function */
    		                                 IOPCTL_PIO_PUPD_DI |
    		                                 /* Enable pull-down function */
    		                                 IOPCTL_PIO_PULLDOWN_EN |
    		                                 /* Enables input buffer function */
    		                                 IOPCTL_PIO_INBUF_EN |
    		                                 /* Normal mode */
    		                                 IOPCTL_PIO_SLEW_RATE_NORMAL |
    		                                 /* Full drive enable */
    		                                 IOPCTL_PIO_FULLDRIVE_EN |
    		                                 /* Analog mux is disabled */
    		                                 IOPCTL_PIO_ANAMUX_DI |
    		                                 /* Pseudo Output Drain is disabled */
    		                                 IOPCTL_PIO_PSEDRAIN_DI |
    		                                 /* Input function is not inverted */
    		                                 IOPCTL_PIO_INV_DI);
    /* PORT1 PIN14 (coords: N2) is configured as FLEXSPI0B_DATA3 */
    IOPCTL_PinMuxSet(IOPCTL, BOARD_INITFLEXSPI0APINS_QSPI_A_DATA3_PORT, BOARD_INITFLEXSPI0APINS_QSPI_A_DATA3_PIN, QSPI_A_DATA3);

    const uint32_t QSPI_A_SCK = (/* Pin is configured as FLEXSPI0B_SCLK */
    		IOPCTL_PIO_FUNC1 |
    		                                /* Disable pull-up / pull-down function */
    		                                IOPCTL_PIO_PUPD_DI |
    		                                /* Enable pull-down function */
    		                                IOPCTL_PIO_PULLDOWN_EN |
    		                                /* Enables input buffer function */
    		                                IOPCTL_PIO_INBUF_EN |
    		                                /* Normal mode */
    		                                IOPCTL_PIO_SLEW_RATE_NORMAL |
    		                                /* Full drive enable */
    		                                IOPCTL_PIO_FULLDRIVE_EN |
    		                                /* Analog mux is disabled */
    		                                IOPCTL_PIO_ANAMUX_DI |
    		                                /* Pseudo Output Drain is disabled */
    		                                IOPCTL_PIO_PSEDRAIN_DI |
    		                                /* Input function is not inverted */
    		                                IOPCTL_PIO_INV_DI);
    /* PORT1 PIN29 (coords: U3) is configured as FLEXSPI0B_SCLK */
    IOPCTL_PinMuxSet(IOPCTL, BOARD_INITFLEXSPI0APINS_QSPI_A_SCK_PORT, BOARD_INITFLEXSPI0APINS_QSPI_A_SCK_PIN, QSPI_A_SCK);

    const uint32_t QSPI_A_CS0 = (/* Pin is configured as FLEXSPI0B_SS0_N */
    		IOPCTL_PIO_FUNC1 |
    		                               /* Disable pull-up / pull-down function */
    		                               IOPCTL_PIO_PUPD_DI |
    		                               /* Enable pull-down function */
    		                               IOPCTL_PIO_PULLDOWN_EN |
    		                               /* Enables input buffer function */
    		                               IOPCTL_PIO_INBUF_EN |
    		                               /* Normal mode */
    		                               IOPCTL_PIO_SLEW_RATE_NORMAL |
    		                               /* Full drive enable */
    		                               IOPCTL_PIO_FULLDRIVE_EN |
    		                               /* Analog mux is disabled */
    		                               IOPCTL_PIO_ANAMUX_DI |
    		                               /* Pseudo Output Drain is disabled */
    		                               IOPCTL_PIO_PSEDRAIN_DI |
    		                               /* Input function is not inverted */
    		                               IOPCTL_PIO_INV_DI);
    /* PORT2 PIN19 (coords: T2) is configured as FLEXSPI0B_SS0_N */
    IOPCTL_PinMuxSet(IOPCTL, BOARD_INITFLEXSPIFLASHPINS_QSPI_A_CS0_PORT, BOARD_INITFLEXSPIFLASHPINS_QSPI_A_CS0_PIN, QSPI_A_CS0);
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitScoPins:
- options: {callFromInitBoot: 'true', coreID: cm33, enableClock: 'true'}
- pin_list:
  - {pin_num: G16, peripheral: FLEXCOMM5, signal: SCK, pin_signal: PIO1_3/FC5_SCK, pupdena: disabled, pupdsel: pullDown, ibena: enabled, slew_rate: normal, drive: full,
    amena: disabled, odena: disabled, iiena: disabled}
  - {pin_num: G17, peripheral: FLEXCOMM5, signal: TXD_SCL_MISO_WS, pin_signal: PIO1_4/FC5_TXD_SCL_MISO_WS, pupdena: disabled, pupdsel: pullDown, ibena: enabled, slew_rate: normal,
    drive: full, amena: disabled, odena: disabled, iiena: disabled}
  - {pin_num: J16, peripheral: FLEXCOMM5, signal: RXD_SDA_MOSI_DATA, pin_signal: PIO1_5/FC5_RXD_SDA_MOSI_DATA, pupdena: disabled, pupdsel: pullDown, ibena: enabled,
    slew_rate: normal, drive: full, amena: disabled, odena: disabled, iiena: disabled}
  - {pin_num: D6, peripheral: FLEXCOMM2, signal: RXD_SDA_MOSI_DATA, pin_signal: PIO0_16/FC2_RXD_SDA_MOSI_DATA/SCT0_GPI2/SCT0_OUT2/CTIMER2_MAT2/I2S_BRIDGE_DATA_IN/SEC_PIO0_16,
    pupdena: disabled, pupdsel: pullDown, ibena: enabled, slew_rate: normal, drive: full, amena: disabled, odena: disabled, iiena: disabled}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */



#endif //gill for pmic

#endif
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
