/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define IOPCTL_PIO_ANAMUX_DI 0x00u        /*!<@brief Analog mux is disabled */
#define IOPCTL_PIO_FULLDRIVE_DI 0x00u     /*!<@brief Normal drive */
#define IOPCTL_PIO_FUNC0 0x00u            /*!<@brief Selects pin function 0 */
#define IOPCTL_PIO_FUNC1 0x01u            /*!<@brief Selects pin function 1 */
#define IOPCTL_PIO_INBUF_DI 0x00u         /*!<@brief Disable input buffer function */
#define IOPCTL_PIO_INBUF_EN 0x40u         /*!<@brief Enables input buffer function */
#define IOPCTL_PIO_INV_DI 0x00u           /*!<@brief Input function is not inverted */
#define IOPCTL_PIO_PSEDRAIN_DI 0x00u      /*!<@brief Pseudo Output Drain is disabled */
#define IOPCTL_PIO_PULLDOWN_EN 0x00u      /*!<@brief Enable pull-down function */
#define IOPCTL_PIO_PUPD_DI 0x00u          /*!<@brief Disable pull-up / pull-down function */
#define IOPCTL_PIO_SLEW_RATE_NORMAL 0x00u /*!<@brief Normal mode */

/*! @name FC0_TXD_SCL_MISO_WS (coord G2), J16[1]/U27[3]/U9[12]
  @{ */
/* Routed pin properties */
/*!
 * @brief Peripheral name */
#define BOARD_INITPINS_DEBUG_UART_TXD_PERIPHERAL FLEXCOMM0
/*!
 * @brief Signal name */
#define BOARD_INITPINS_DEBUG_UART_TXD_SIGNAL TXD_SCL_MISO_WS
/*!
 * @brief PORT peripheral base pointer */
#define BOARD_INITPINS_DEBUG_UART_TXD_PORT 0U
/*!
 * @brief PORT pin number */
#define BOARD_INITPINS_DEBUG_UART_TXD_PIN 1U
/*!
 * @brief PORT pin mask */
#define BOARD_INITPINS_DEBUG_UART_TXD_PIN_MASK (1U << 1U)
/* @} */

/*! @name FC0_RXD_SDA_MOSI_DATA (coord G4), JP40[2]
  @{ */
/* Routed pin properties */
/*!
 * @brief Peripheral name */
#define BOARD_INITPINS_DEBUG_UART_RXD_PERIPHERAL FLEXCOMM0
/*!
 * @brief Signal name */
#define BOARD_INITPINS_DEBUG_UART_RXD_SIGNAL RXD_SDA_MOSI_DATA
/*!
 * @brief PORT peripheral base pointer */
#define BOARD_INITPINS_DEBUG_UART_RXD_PORT 0U
/*!
 * @brief PORT pin number */
#define BOARD_INITPINS_DEBUG_UART_RXD_PIN 2U
/*!
 * @brief PORT pin mask */
#define BOARD_INITPINS_DEBUG_UART_RXD_PIN_MASK (1U << 2U)
/* @} */

/*! @name PIO0_26 (coord A2), FUN_KEY1_N
  @{ */
/* Routed pin properties */
#define BOARD_INITPINS_LED_BLUE_PERIPHERAL GPIO           /*!<@brief Peripheral name */
#define BOARD_INITPINS_LED_BLUE_SIGNAL PIO0               /*!<@brief Signal name */
#define BOARD_INITPINS_LED_BLUE_CHANNEL 26                /*!<@brief Signal channel */

/* Symbols to be used with GPIO driver */
#define BOARD_INITPINS_LED_BLUE_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define BOARD_INITPINS_LED_BLUE_GPIO_PIN_MASK (1U << 26U) /*!<@brief GPIO pin mask */
#define BOARD_INITPINS_LED_BLUE_PORT 0U                   /*!<@brief PORT peripheral base pointer */
#define BOARD_INITPINS_LED_BLUE_PIN 26U                   /*!<@brief PORT pin number */
#define BOARD_INITPINS_LED_BLUE_PIN_MASK (1U << 26U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void); /* Function assigned for the Cortex-M33 */

#define IOPCTL_PIO_ANAMUX_DI 0x00u        /*!<@brief Analog mux is disabled */
#define IOPCTL_PIO_FULLDRIVE_DI 0x00u     /*!<@brief Normal drive */
#define IOPCTL_PIO_FUNC0 0x00u            /*!<@brief Selects pin function 0 */
#define IOPCTL_PIO_FUNC1 0x01u            /*!<@brief Selects pin function 1 */
#define IOPCTL_PIO_INBUF_DI 0x00u         /*!<@brief Disable input buffer function */
#define IOPCTL_PIO_INBUF_EN 0x40u         /*!<@brief Enables input buffer function */
#define IOPCTL_PIO_INV_DI 0x00u           /*!<@brief Input function is not inverted */
#define IOPCTL_PIO_PSEDRAIN_DI 0x00u      /*!<@brief Pseudo Output Drain is disabled */
#define IOPCTL_PIO_PULLDOWN_EN 0x00u      /*!<@brief Enable pull-down function */
#define IOPCTL_PIO_PUPD_DI 0x00u          /*!<@brief Disable pull-up / pull-down function */
#define IOPCTL_PIO_SLEW_RATE_NORMAL 0x00u /*!<@brief Normal mode */

/*! @name I3C0_SCL (coord N17), PCA9422_I2C_SCL
  @{ */
/* Routed pin properties */
#define PCA9422_I3C_I3C_ICM_SCL_PERIPHERAL I3C            /*!<@brief Peripheral name */
#define PCA9422_I3C_I3C_ICM_SCL_SIGNAL SCL                /*!<@brief Signal name */
#define PCA9422_I3C_I3C_ICM_SCL_PORT 2U                   /*!<@brief PORT peripheral base pointer */
#define PCA9422_I3C_I3C_ICM_SCL_PIN 29U                   /*!<@brief PORT pin number */
#define PCA9422_I3C_I3C_ICM_SCL_PIN_MASK (1U << 29U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*! @name I3C0_SDA (coord P16), PCA9422_I2C_SDA
  @{ */
/* Routed pin properties */
#define PCA9422_I3C_I3C_ICM_SDA_PERIPHERAL I3C            /*!<@brief Peripheral name */
#define PCA9422_I3C_I3C_ICM_SDA_SIGNAL SDA                /*!<@brief Signal name */
#define PCA9422_I3C_I3C_ICM_SDA_PORT 2U                   /*!<@brief PORT peripheral base pointer */
#define PCA9422_I3C_I3C_ICM_SDA_PIN 30U                   /*!<@brief PORT pin number */
#define PCA9422_I3C_I3C_ICM_SDA_PIN_MASK (1U << 30U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*! @name PIO1_9 (coord B1), J28[1]
  @{ */
/* Routed pin properties */
#define PCA9422_I3C_DVS_CTR0_PERIPHERAL GPIO          /*!<@brief Peripheral name */
#define PCA9422_I3C_DVS_CTR0_SIGNAL PIO1              /*!<@brief Signal name */
#define PCA9422_I3C_DVS_CTR0_CHANNEL 9                /*!<@brief Signal channel */

/* Symbols to be used with GPIO driver */
#define PCA9422_I3C_DVS_CTR0_GPIO GPIO                /*!<@brief GPIO peripheral base pointer */
#define PCA9422_I3C_DVS_CTR0_GPIO_PIN_MASK (1U << 9U) /*!<@brief GPIO pin mask */
#define PCA9422_I3C_DVS_CTR0_PORT 1U                  /*!<@brief PORT peripheral base pointer */
#define PCA9422_I3C_DVS_CTR0_PIN 9U                   /*!<@brief PORT pin number */
#define PCA9422_I3C_DVS_CTR0_PIN_MASK (1U << 9U)      /*!<@brief PORT pin mask */
                                                      /* @} */

/*! @name PIO0_29 (coord B10), J27[2]
  @{ */
/* Routed pin properties */
#define PCA9422_I3C_DVS_CTR1_PERIPHERAL GPIO           /*!<@brief Peripheral name */
#define PCA9422_I3C_DVS_CTR1_SIGNAL PIO0               /*!<@brief Signal name */
#define PCA9422_I3C_DVS_CTR1_CHANNEL 29                /*!<@brief Signal channel */

/* Symbols to be used with GPIO driver */
#define PCA9422_I3C_DVS_CTR1_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define PCA9422_I3C_DVS_CTR1_GPIO_PIN_MASK (1U << 29U) /*!<@brief GPIO pin mask */
#define PCA9422_I3C_DVS_CTR1_PORT 0U                   /*!<@brief PORT peripheral base pointer */
#define PCA9422_I3C_DVS_CTR1_PIN 29U                   /*!<@brief PORT pin number */
#define PCA9422_I3C_DVS_CTR1_PIN_MASK (1U << 29U)      /*!<@brief PORT pin mask */
                                                       /* @} */

/*! @name PIO2_31 (coord B6), J18[3]
  @{ */
/* Routed pin properties */
#define PCA9422_I3C_DVS_CTR2_PERIPHERAL GPIO           /*!<@brief Peripheral name */
#define PCA9422_I3C_DVS_CTR2_SIGNAL PIO2               /*!<@brief Signal name */
#define PCA9422_I3C_DVS_CTR2_CHANNEL 31                /*!<@brief Signal channel */

/* Symbols to be used with GPIO driver */
#define PCA9422_I3C_DVS_CTR2_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define PCA9422_I3C_DVS_CTR2_GPIO_PIN_MASK (1U << 31U) /*!<@brief GPIO pin mask */
#define PCA9422_I3C_DVS_CTR2_PORT 2U                   /*!<@brief PORT peripheral base pointer */
#define PCA9422_I3C_DVS_CTR2_PIN 31U                   /*!<@brief PORT pin number */
#define PCA9422_I3C_DVS_CTR2_PIN_MASK (1U << 31U)      /*!<@brief PORT pin mask */
                                                       /* @} */

/*! @name PIO2_27 (coord M14), U13[A2]
  @{ */
/* Routed pin properties */
#define PCA9422_I3C_SLEEP_MODE0_PERIPHERAL GPIO           /*!<@brief Peripheral name */
#define PCA9422_I3C_SLEEP_MODE0_SIGNAL PIO2               /*!<@brief Signal name */
#define PCA9422_I3C_SLEEP_MODE0_CHANNEL 27                /*!<@brief Signal channel */

/* Symbols to be used with GPIO driver */
#define PCA9422_I3C_SLEEP_MODE0_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define PCA9422_I3C_SLEEP_MODE0_GPIO_PIN_MASK (1U << 27U) /*!<@brief GPIO pin mask */
#define PCA9422_I3C_SLEEP_MODE0_PORT 2U                   /*!<@brief PORT peripheral base pointer */
#define PCA9422_I3C_SLEEP_MODE0_PIN 27U                   /*!<@brief PORT pin number */
#define PCA9422_I3C_SLEEP_MODE0_PIN_MASK (1U << 27U)      /*!<@brief PORT pin mask */
                                                          /* @} */

/*! @name PIO0_24 (coord B9), J19[18]/J38[26]
  @{ */
/* Routed pin properties */
#define PCA9422_I3C_STBY_MODE1_PERIPHERAL GPIO           /*!<@brief Peripheral name */
#define PCA9422_I3C_STBY_MODE1_SIGNAL PIO0               /*!<@brief Signal name */
#define PCA9422_I3C_STBY_MODE1_CHANNEL 24                /*!<@brief Signal channel */

/* Symbols to be used with GPIO driver */
#define PCA9422_I3C_STBY_MODE1_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define PCA9422_I3C_STBY_MODE1_GPIO_PIN_MASK (1U << 24U) /*!<@brief GPIO pin mask */
#define PCA9422_I3C_STBY_MODE1_PORT 0U                   /*!<@brief PORT peripheral base pointer */
#define PCA9422_I3C_STBY_MODE1_PIN 24U                   /*!<@brief PORT pin number */
#define PCA9422_I3C_STBY_MODE1_PIN_MASK (1U << 24U)      /*!<@brief PORT pin mask */
                                                         /* @} */

/*! @name PIO2_28 (coord N15), Q1[1]
  @{ */
/* Routed pin properties */
#define PCA9422_I3C_PCA9422_INTB_PERIPHERAL GPIO           /*!<@brief Peripheral name */
#define PCA9422_I3C_PCA9422_INTB_SIGNAL PIO2               /*!<@brief Signal name */
#define PCA9422_I3C_PCA9422_INTB_CHANNEL 28                /*!<@brief Signal channel */

/* Symbols to be used with GPIO driver */
#define PCA9422_I3C_PCA9422_INTB_GPIO GPIO                 /*!<@brief GPIO peripheral base pointer */
#define PCA9422_I3C_PCA9422_INTB_GPIO_PIN_MASK (1U << 28U) /*!<@brief GPIO pin mask */
#define PCA9422_I3C_PCA9422_INTB_PORT 2U                   /*!<@brief PORT peripheral base pointer */
#define PCA9422_I3C_PCA9422_INTB_PIN 28U                   /*!<@brief PORT pin number */
#define PCA9422_I3C_PCA9422_INTB_PIN_MASK (1U << 28U)      /*!<@brief PORT pin mask */
                                                           /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void PCA9422_I3C(void); /* Function assigned for the Cortex-M33 */

#define IOPCTL_PIO_ANAMUX_DI 0x00u        /*!<@brief Analog mux is disabled */
#define IOPCTL_PIO_FULLDRIVE_EN 0x0100u   /*!<@brief Full drive enable */
#define IOPCTL_PIO_FUNC1 0x01u            /*!<@brief Selects pin function 1 */
#define IOPCTL_PIO_INBUF_EN 0x40u         /*!<@brief Enables input buffer function */
#define IOPCTL_PIO_INV_DI 0x00u           /*!<@brief Input function is not inverted */
#define IOPCTL_PIO_PSEDRAIN_DI 0x00u      /*!<@brief Pseudo Output Drain is disabled */
#define IOPCTL_PIO_PULLDOWN_EN 0x00u      /*!<@brief Enable pull-down function */
#define IOPCTL_PIO_PUPD_DI 0x00u          /*!<@brief Disable pull-up / pull-down function */
#define IOPCTL_PIO_SLEW_RATE_NORMAL 0x00u /*!<@brief Normal mode */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void AMP_I2S(void); /* Function assigned for the Cortex-M33 */

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
