/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define IOPCTL_PIO_ANAMUX_DI 0x00u        /*!<@brief Analog mux is disabled */
#define IOPCTL_PIO_FULLDRIVE_DI 0x00u     /*!<@brief Normal drive */
#define IOPCTL_PIO_FUNC1 0x01u            /*!<@brief Selects pin function 1 */
#define IOPCTL_PIO_INBUF_EN 0x40u         /*!<@brief Enables input buffer function */
#define IOPCTL_PIO_INV_DI 0x00u           /*!<@brief Input function is not inverted */
#define IOPCTL_PIO_PSEDRAIN_DI 0x00u      /*!<@brief Pseudo Output Drain is disabled */
#define IOPCTL_PIO_PULLDOWN_EN 0x00u      /*!<@brief Enable pull-down function */
#define IOPCTL_PIO_PUPD_DI 0x00u          /*!<@brief Disable pull-up / pull-down function */
#define IOPCTL_PIO_SLEW_RATE_NORMAL 0x00u /*!<@brief Normal mode */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void); /* Function assigned for the Cortex-M33 */

#define IOPCTL_PIO_ANAMUX_DI 0x00u        /*!<@brief Analog mux is disabled */
#define IOPCTL_PIO_FULLDRIVE_EN 0x0100u   /*!<@brief Full drive enable */
#define IOPCTL_PIO_FUNC6 0x06u            /*!<@brief Selects pin function 6 */
#define IOPCTL_PIO_INBUF_EN 0x40u         /*!<@brief Enables input buffer function */
#define IOPCTL_PIO_INV_DI 0x00u           /*!<@brief Input function is not inverted */
#define IOPCTL_PIO_PSEDRAIN_DI 0x00u      /*!<@brief Pseudo Output Drain is disabled */
#define IOPCTL_PIO_PULLDOWN_EN 0x00u      /*!<@brief Enable pull-down function */
#define IOPCTL_PIO_PUPD_DI 0x00u          /*!<@brief Disable pull-up / pull-down function */
#define IOPCTL_PIO_SLEW_RATE_NORMAL 0x00u /*!<@brief Normal mode */

/*! @name FLEXSPI0B_DATA0 (coord E5), U19[D3]
  @{ */
/* Routed pin properties */
#define BOARD_INITFLEXSPI0BPINS_QSPI_B_DATA0_PERIPHERAL FLEXSPI        /*!<@brief Peripheral name */
#define BOARD_INITFLEXSPI0BPINS_QSPI_B_DATA0_SIGNAL FLEXSPI_B_DATA0    /*!<@brief Signal name */
#define BOARD_INITFLEXSPI0BPINS_QSPI_B_DATA0_PORT 1U                   /*!<@brief PORT peripheral base pointer */
#define BOARD_INITFLEXSPI0BPINS_QSPI_B_DATA0_PIN 11U                   /*!<@brief PORT pin number */
#define BOARD_INITFLEXSPI0BPINS_QSPI_B_DATA0_PIN_MASK (1U << 11U)      /*!<@brief PORT pin mask */
                                                                       /* @} */

/*! @name FLEXSPI0B_DATA3 (coord D4), U19[D4]
  @{ */
/* Routed pin properties */
#define BOARD_INITFLEXSPI0BPINS_QSPI_B_DATA3_PERIPHERAL FLEXSPI        /*!<@brief Peripheral name */
#define BOARD_INITFLEXSPI0BPINS_QSPI_B_DATA3_SIGNAL FLEXSPI_B_DATA3    /*!<@brief Signal name */
#define BOARD_INITFLEXSPI0BPINS_QSPI_B_DATA3_PORT 1U                   /*!<@brief PORT peripheral base pointer */
#define BOARD_INITFLEXSPI0BPINS_QSPI_B_DATA3_PIN 14U                   /*!<@brief PORT pin number */
#define BOARD_INITFLEXSPI0BPINS_QSPI_B_DATA3_PIN_MASK (1U << 14U)      /*!<@brief PORT pin mask */
                                                                       /* @} */

/*! @name FLEXSPI0B_DATA5 (coord B1), U19[E3]
  @{ */
/* Routed pin properties */
#define BOARD_INITFLEXSPI0BPINS_QSPI_B_DATA5_PERIPHERAL FLEXSPI        /*!<@brief Peripheral name */
#define BOARD_INITFLEXSPI0BPINS_QSPI_B_DATA5_SIGNAL FLEXSPI_B_DATA5    /*!<@brief Signal name */
#define BOARD_INITFLEXSPI0BPINS_QSPI_B_DATA5_PORT 2U                   /*!<@brief PORT peripheral base pointer */
#define BOARD_INITFLEXSPI0BPINS_QSPI_B_DATA5_PIN 18U                   /*!<@brief PORT pin number */
#define BOARD_INITFLEXSPI0BPINS_QSPI_B_DATA5_PIN_MASK (1U << 18U)      /*!<@brief PORT pin mask */
                                                                       /* @} */

/*! @name FLEXSPI0B_SS0_N (coord A2), U19[C2]
  @{ */
/* Routed pin properties */
#define BOARD_INITFLEXSPI0BPINS_QSPI_B_CS0_PERIPHERAL FLEXSPI        /*!<@brief Peripheral name */
#define BOARD_INITFLEXSPI0BPINS_QSPI_B_CS0_SIGNAL FLEXSPI_B_SS0_B    /*!<@brief Signal name */
#define BOARD_INITFLEXSPI0BPINS_QSPI_B_CS0_PORT 2U                   /*!<@brief PORT peripheral base pointer */
#define BOARD_INITFLEXSPI0BPINS_QSPI_B_CS0_PIN 19U                   /*!<@brief PORT pin number */
#define BOARD_INITFLEXSPI0BPINS_QSPI_B_CS0_PIN_MASK (1U << 19U)      /*!<@brief PORT pin mask */
                                                                     /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitFlexSPI0BPins(void); /* Function assigned for the Cortex-M33 */

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
